### ISSUE TITLE
Versioning issue with aws-sdk

### ISSUE THREAD

**Issue by rtm** [automategreen/dynamoose#10]
I notice the published version (the one you get with 'npm install', with the tag 0.3.1) still refers to an earlier version of aws-sdk (2.0.0-rc.17), but that a commit from six months ago bumps aws-sdk up to 2.0.10. WIth the published version, I am running into some AWS-related issues that i think might be related to node 0.11. I changed my package.json entry to say '"dynamoose": "git://github.com/automategreen/dynamoose"' and all is well.

Is there something I'm missing or it is OK to do what I'm doing, and/or should there be a 0.3.2 which reflects the aws-sdk update?

**Comment by brandongoode** [comment]
I've been planning to update the release for some time (something like 6 months) but keep forgetting to do it.  Thanks for bringing it to my attention.  I using the repo directly to verify changes are stable; however, you shouldn't need to.  I'll push an update shortly.

**Comment by brandongoode** [comment]
0.3.2 is published to npm.
