### ISSUE TITLE
Automatic pagination/aggregation for Query and Scan

### ISSUE THREAD

**Issue by strygin** [automategreen/dynamoose#102]
I'm going to implement automatic paginated request wrapper built-in in Query and Scan, because of DynamoDB chuck's size limit of 1Mb. Even if you just need to get a `count` of matching rows (without returning any other data), Query and Scan cannot return correct results in a single request if it goes thru more 1MB of data (keys or rows) on its side for analyzing. For example `count` will be unaggregated. Pretty hard to demonstrate it using tests, because I need to feed a test DB with 10's of thousands rows in order for an index footprint to overflow 1Mb.

**Comment by strygin** [comment]
If you wonder which `count` I'm talking about, checkout this PR: #101

**Comment by brandongoode** [comment]
I overlooked this.  That would be great.  Let me know if you need any help.

**Comment by strygin** [comment]
Will work on it this weekend

**Comment by yusufar** [comment]
@brandongoode when [this](https://github.com/automategreen/dynamoose/pull/101) is going to come as a new version?

**Comment by brandongoode** [comment]
@yusufar No ETA on the release date.  I have to find some time to clean up some loose ends and then will be working on the next release.  

For now, you can pull directly from the repo.  I try to make sure master is always stable, but I would recommend referencing a commit to make sure changes don't impact you.

```json
"dependencies": {
  "package": "git://github.com/automategreen/dynamoose.git#commit"
}
```
