### ISSUE TITLE
Help? Query bafflement

### ISSUE THREAD

**Issue by reselbob** [automategreen/dynamoose#104]
Hi:

I am constructing a query:

  ```
const lim = validationHelper.getValidPageSize(options.pageSize);
  return validationHelper.getValidStartKey(options.startKey)
    .then(sKey => {
      const query = Entry.query('userId').eq(options.userId).limit(lim);

      if (!options.activityType) {
        query.filter('entryDateTime')
          .between(sDate, eDate);
      }else
      {
        query.filter('quantityType').eq(options.activityType)
          .and()
          .filter('entryDateTime')
          .between(sDate, eDate);
      }
      if (sKey){
        query.startAt(sKey);
      }
```
In the table I can see **83** records according to userId and activityType defined. Yet, as I run the query, only **50** records come back, consistently

Here are the values for the variables:

`sKey = null`
`options.userId = '0444142e-8631-4443-8e84-bdc7c56719ad'`
`lim = 100`
`sDate = 'Wed Jan 31 2007 12:54:43 GMT-0800 (PST)'`
`eDate = 'Sun Jan 31 2027 12:54:43 GMT-0800 (PST)'`
`options.activityType = 'water`

Any help will be greatly appreciated.

Thanks in advance.

**Comment by brandongoode** [comment]
Amazon limits the query results to 1MB regardless of the limit. Depending on your data size it could be that 50 items are 1MB.  Check the results to see if there is a `lastKey`.  If there is, you'll need to make the same query with `.startAt(lastKey)`.

https://github.com/automategreen/dynamoose#querylimitlimit

**Comment by reselbob** [comment]
The data return is quite small. Would it be helpful to post the data here?

**Comment by brandongoode** [comment]
I wonder if it could be the dates.  Are you using date strings or the `Date` object?

If you could share the data, that would be great.

**Comment by brandongoode** [comment]
Also the schema would help.

**Comment by reselbob** [comment]
[entry.txt](https://github.com/automategreen/dynamoose/files/745375/entry.txt)

**Comment by reselbob** [comment]
The byte size of the return is : 392
info: { message: 'Responding 200 for getEntries',
  result: '{"lastKey":{"id":{"S":"d1d1e929-f89d-4a6e-be4d-17fe4a62f40f"}},"items":[{"id":"9f7f2b07-7641-4b61-90e8-d7796f03334e","entryDateTime":"2017-02-01T15:57:24.320Z","userId":"7848949a-aceb-41a8-8103-ffe100e6b287","clientName":"DEV","clientKey":"2","messageId":"e39a3155-8171-4747-98bb-d3b959e82d48","userName":"aurandzachariah","quantityType":"steps","quantity":2308,"createdAt":"2017-02-01T15:57:24.724Z","updatedAt":"2017-02-01T15:57:24.724Z","device":"manual"}]}',
  correlationId: '888cb406-5bc3-4fdd-9e84-09c868431731' } 'Object.module.exports.sendResultResponseSync' '/Users/reselbob/Documents/source-tree/challenges/utilities/responseHelper.js' '45:10'
AssertionError: expected 1 to equal 20

**Comment by reselbob** [comment]
Does this help?

**Comment by brandongoode** [comment]
So the 1MB is based on the number of items queried before the filters are applied.  Since you are using `.filter` the data may be hitting the 1MB limit.   Since `entryDateTime` is the range key, you could use `.where` instead of `.filter`.  `.where` is before the 1MB limit and `.filter` is after.

**Comment by reselbob** [comment]
ok, let me try where

**Comment by reselbob** [comment]
Like so:

```
  if (!options.activityType) {
        scan = Entry.scan('userId').eq(options.userId).limit(lim)
          .where('entryDateTime')
          .between(sDate, eDate);
      } else {
        scan = Entry.scan('quantityType').eq(options.activityType).limit(lim)
          .where('entryDateTime')
          .between(sDate, eDate)
          .filter('userId').eq(options.userId);
      }

      if (sKey) {
        scan.startAt(sKey);
      }
```

**Comment by brandongoode** [comment]
Yep

**Comment by reselbob** [comment]
No cigar:

AssertionError: expected 4 to equal 20

**Comment by reselbob** [comment]
let me take off the date clauses and see what happens

**Comment by reselbob** [comment]
Also, I need to point out, I am working using the local dynamodb

**Comment by brandongoode** [comment]
went from 1 to 4 -- progress ;-)

Try setting userId to null and leaving the dates.

**Comment by brandongoode** [comment]
The user is another filter that may be causing the 1MB limit.

**Comment by reselbob** [comment]
if (!options.activityType) {
        scan = Entry.scan('userId').eq(options.userId).limit(lim)
          .where('entryDateTime')
          .between(sDate, eDate);
      } else {
        scan = Entry.scan('quantityType').eq(options.activityType).limit(lim)
          .where('entryDateTime')
          .between(sDate, eDate)
         .and()
          //.filter('userId').eq(options.userId);
      }

Nope

AssertionError: expected 15 to equal 20

Let me drop the table an make sure only under 1 MB is in there

**Comment by reselbob** [comment]
nope:

AssertionError: expected 9 to equal 20

Let me go up against DynamoDB on AWS

**Comment by brandongoode** [comment]
I missed the fact that you changed to scan.  Can you go back to the `.query` with the `.where`.  Scan treats `.where` and `.filter` as the same (i.e. as `.filter`).

**Comment by brandongoode** [comment]
Something like:

```js
    const query = Entry.query('userId').eq(options.userId).limit(lim);

    query.filter('entryDateTime')
        .between(sDate, eDate);

    if (options.activityType) {
      query.filter('quantityType').eq(options.activityType);
    }
    if (sKey){
      query.startAt(sKey);
    }

```

**Comment by reselbob** [comment]
Using the above, nope
AssertionError: expected 8 to equal 20

Let me bind to AWS

**Comment by reselbob** [comment]
Yeah, I am replicating the bad behavior directly against AWS. Question: Do I need to be using an and() clause in this:

```
 const query = Entry.query('userId').eq(options.userId).limit(lim);

      query.filter('entryDateTime')
        .between(sDate, eDate);

      if (options.activityType) {
        query.filter('quantityType').eq(options.activityType);
      }
      if (sKey){
        query.startAt(sKey);
      }
```

**Comment by reselbob** [comment]
I have some more data:

I have a table with 57 eligible records.

This test, which is a configuration of the query:

```
  it('Can search according to PageSize and QuantityType via Processors', done => {
    const queryCount = 100
    const options = {};
    options.activityType = 'steps';
    options.pageSize = queryCount
    options.userId = user.id;
    serviceProcessor.getChallengesUserEntries(options)
      .then(result => {
          expect(result).to.be.an('array');
          console.log(`Number of items ${result.length}`);
        done();
      })
      .catch(done);
  });
```
returns the expected number of records
Number of items 57

When I drop  `const queryCount = 90`
Number of items 54

When I drop to 80,
Number of items 49

When I drop to 70,
Number of items 41

But, when I up to 200,
Number of items 57

maybe this helps.

**Comment by reselbob** [comment]
But!!! When I turn off the activityType parameter, all is well, like so:

```
    // options.activityType = 'steps';
    options.pageSize = queryCount
    options.userId = user.id
```

**Comment by brandongoode** [comment]
Here's how the limit option works with filters which explains the behavior:

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#ScanQueryLimit

> **Limit**
> 
>The DynamoDB Query and Scan APIs allow a Limit value to restrict the size of the results.
>
>In a request, set the Limit parameter to the number of items that you want DynamoDB to process before returning results.
>
>In a response, DynamoDB returns all the matching results within the scope of the Limit value. For example, if you issue a Query or a Scan request with a Limit value of 6 and without a filter expression, DynamoDB returns the first six items in the table that match the specified key conditions in the request (or just the first six items in the case of a Scan with no filter). If you also supply a FilterExpression value, DynamoDB will return the items in the first six that also match the filter requirements (the number of results returned will be less than or equal to 6).
>
>For either a Query or Scan operation, DynamoDB might return a LastEvaluatedKey value if the operation did not return all matching items in the table. To get the full count of items that match, take the LastEvaluatedKey value from the previous request and use it as the ExclusiveStartKey value in the next request. Repeat this until DynamoDB no longer returns a LastEvaluatedKey value.

**Comment by reselbob** [comment]
Thank you for you kind patience with me.

**Comment by brandongoode** [comment]
Glad to help

@strygin is already working on it, #102

**Comment by ahmad-ben** [comment]
@brandongoode First thank u, second so basically we can't specify how many items will be returned after the where function run, we just have the ability to specify how many elements will return in the first place to apply a filter on them, right??.

**Comment by fishcharlie** [comment]
@ahmad-ben Please do not ping threads that are over 7 years old. This issue is resolved and will be locked.
