### ISSUE TITLE
Querying Secondary Indexes

### ISSUE THREAD

**Issue by remmons** [automategreen/dynamoose#106]
I might be missing something in the docs but is there a way to specify a secondary index to query?

**Comment by brandongoode** [comment]
Dynamoose will search for the secondary index based on the attributes in the `.query(hast_key)` and `.where(range_key)` statements.

**Comment by remmons** [comment]
Cool. That all is making sense. When looking at Scan.js, it looks like all the secondary index hashKey logic is missing and it will only do full table scans. Testing it out by hard coding the IndexName attribute in the scanReq object gets the result I want but I'm not sure the best way to add this functionality into your library. Any suggestions?

**Comment by brandongoode** [comment]
Scan always looks at the full table and doesn't use the indexes at all.

**Comment by remmons** [comment]
Your right. Sorry about that, still a bit new to dynamo.

**Comment by igorkosta** [comment]
@brandongoode should it work with an Inverted GSI out of the box?

**Comment by fishcharlie** [comment]
@igorkosta This issue is over 4 years old. A **LOT** has changed on the project since then. Please submit a new issue with all relevant information so I can help take a look at this.
