### ISSUE TITLE
Does Dynamoose support saving non attribute data?

### ISSUE THREAD

**Issue by kcjl519** [automategreen/dynamoose#107]
I have defined some basic attributes of the model, for example.

```javascript
var Cat = dynamoose.model('Cat', { id: Number, name: String });
```

But when I do something like

```javascript
var oscar = new Cat({id: 1, name: 'oscar', info: {some: 1, other: 2, details: 3}});
oscar.save()
```

info, never gets saved. How can I save data that's not defined in the schema?

**Comment by brandongoode** [comment]
Dynamoose doesn't support saving data not defined in the schema.

It could be done but would required modifying `Schema.prototype.toDynamo` and `Schema.prototype.parseDynamo` to handled all properties and apply a default `Object` attribute to the properties that don't match. 

Something like the changes below. If you have time to test and document, I would be happy to merge a PR.

```js
Schema.prototype.toDynamo = function(model) {

  var dynamoObj = {};

  for(var name in model) {
    var attr = this.attributes[name];

    if(!attr & this.options.saveUnknown) {
      attr = Attribute.create(this, name, Object);
      this.attributes[name] = attr;
    }

    if(attr) {
      attr.setDefault(model);
      var dynamoAttr = attr.toDynamo(model[name], undefined, model);
      if(dynamoAttr) {
        dynamoObj[attr.name] = dynamoAttr;
      }
    }
  }

  debug('toDynamo: %s', JSON.stringify(dynamoObj) );
  return dynamoObj;
};

Schema.prototype.parseDynamo = function(model, dynamoObj) {

  for(var name in dynamoObj) {
    var attr = this.attributes[name];

    if(!attr & this.options.saveUnknown) {
      attr = Attribute.create(this, name, Object);
      this.attributes[name] = attr;
    }

    if(attr) {
      var attrVal = attr.parseDynamo(dynamoObj[name]);
      if(attrVal !== undefined && attrVal !== null){
        model[name] = attrVal;
      }
    }
  }

  debug('parseDynamo: %s',JSON.stringify(model));

  return dynamoObj;

};
```

**Comment by kcjl519** [comment]
Thanks! I'll have a look later next week.

**Comment by kcjl519** [comment]
I'm assuming I'd also have to modify Model.js Operations.getUpdateExpression ?

**Comment by kcjl519** [comment]
Upon some testing, it seems this involves a bigger change.

**Comment by brandongoode** [comment]
I don't think any changes are needed in the `getUpdateExpression` function, but changes are needed to the 3 looks that inject the changes in to the `operations` object. 

The `putAttr`, `deleteAttr`, and `addAttr` all need to have the same check applied as in `toDynamo` above:

```js
if(!attr & this.options.saveUnknown) {
  attr = Attribute.create(this, name, Object);
  this.attributes[name] = attr;
}
```

If you push your the changes to your fork, I would be happy to look them over and see if i can spot the issue.

**Comment by sdrioux** [comment]
Bump. Ran into this same issue.  This would be an awesome addition.
