### ISSUE TITLE
Update Global Secondary Indexes

### ISSUE THREAD

**Issue by brandongoode** [automategreen/dynamoose#11]
Global Secondary Indexes (GSI) enable you to perform more efficient queries. Now, you can add or delete GSIs from your table at any time, instead of just during table creation. GSIs can be added via the DynamoDB console or a simple API call. While the GSI is being added or deleted, the DynamoDB table can still handle live traffic and provide continuous service at the provisioned throughput level. To learn more about Online Indexing, please read our blog or visit the documentation page for more technical and operational details.

**Comment by jottinger** [comment]
brandon, if I understand the issue, basically what needs to happen is this:

* on model initialization, get the metadata from dynamo
* if the dynamo metadata doesn't match the model (and the model is set to.. 'create,' I guess?)...
  * if index exists, delete it
  * create index with model metadata

Would that be an accurate summary of what needs to happen?

**Comment by brandongoode** [comment]
@jottinger Yes that's the idea.  Does this mean you're thinking of creating a PR?

**Comment by jottinger** [comment]
I'm just now getting into Dynamoose - my plan is to do so, but I'm just now
dipping my toes in.

**Comment by brandongoode** [comment]
Cool.  It's a change I've been meaning to make for a while, but haven't had the time.

**Comment by jottinger** [comment]
brandon: what's the nature of the GSIs such that they're not being managed properly? I assume it's not as simple as adding an `index:true` to the schema...

**Comment by brandongoode** [comment]
@jottinger  I'm not 100% sure I understand the question.  The issue is when you add `index` after the table was created.  Dynamoose will compare the schema against the table & indexes in DynamoDB and if they do no match will throw an error.   It should be possible to modify the global indexes on DynamoDB to match the schema.

**Comment by jottinger** [comment]
Okay. What I did was create a table ("Song") with no indexes... save data into it. Then I created another file with the same schema, except with a few columns with `index:true`, saving data into THAT. I had no problems with it.

Does the problem only occur on AWS deployments? Do local dynamo installations not have the problem?

**Comment by jottinger** [comment]
And it looks like that's the case: local dynamo deployment is different than remote in terms of functionality. Gee, thanks, AWS. :)
