### ISSUE TITLE
"createRequired" option on Model.Update doesn't work

### ISSUE THREAD

**Issue by breath103** [automategreen/dynamoose#112]
such as 
```
UserUserRelation.update({user_id: 111759, followee_id: 106089}, {createRequired: true})
```
ignored. i can't really find any code that using that flag on repo also. is it a mistake? maybe simply not implemented yet but has docs already

**Comment by brandongoode** [comment]
createRequired is not in a npm published version of dynomoose.  It will be released in the next version.  For now, you'll need to reference the repo directly:

```json

  "dependencies": {
    "dynamoose": "git://github.com/automategreen/dynamoose.git"
  }
```

**Comment by brandongoode** [comment]
v0.8.0 has been released with this
