### ISSUE TITLE
Query problem when hash key name is "hash"

### ISSUE THREAD

**Issue by AlexanderFillbrunn** [automategreen/dynamoose#115]
I am currently writing some unit tests using a test table where the hash key name is "hash". Using a query like below fails because the query constructor looks for the property hash expecting something like `{hash: {<hashkeyname>: 'somevalue'} }`:
```
Model.query({hash: {eq: 'somevalue'} }, function (err, data) {
  // Do something
});
```
Is there any way this could be fixed so that "hash" does not become kind of a reserved word? If that's not possible, this behaviour should probably be documented somewhere.

**Comment by brandongoode** [comment]
Sorry for the slow response. 

Yes you can fix it by using the following query format:

```js
Model.query('hash').eq('somevalue').exec(function (err, data) { ... });
```
