### ISSUE TITLE
TTL Support

### ISSUE THREAD

**Issue by brandongoode** [automategreen/dynamoose#116]
Wow -- Finally TTL support.  No more date based tables to delete!

https://aws.amazon.com/about-aws/whats-new/2017/02/amazon-dynamodb-now-supports-automatic-item-expiration-with-time-to-live-ttl

 I'm thinking either as an option on the Schema that creates an attribute named `expires` (similar to the timestamp option).  The expires would be a modified `Date` type, because it needs to stored seconds vs the standard milliseconds. 

```js
new Schema({...}, { throughput: 5, expires: 30*24*60*60});
new Schema({...}, { throughput: 5, expires: { name: 'expires', ttl: 30*24*60*60 } });
```

It could be updated by setting the expires attribute to the new date object.

Please let me know how you think it should be implemented.

**Comment by AlexanderFillbrunn** [comment]
As I understand it, the attribute that determines when the record expires is just a normal attribute, meaning it should also support validation, indexes, etc. Maybe something like this should also be allowed:
new Schema({ myexpiryfield: {type: Number, rangeKey: true}, ...}, { throughput: 5, expires: {attr: 'myexpiryfield'}});
Additionally I would suggest that if a new entry is created and the "expires" attribute is given explicitly, the settings in the schema should not apply and the value passed by the user should be used.

**Comment by brandongoode** [comment]
Good ideas.  I agree.   We should support manually defined expires attributes.  The default ttl should only be applied if the attribute is null or undefined.

**Comment by JonathanBristow** [comment]
@brandongoode I'm really looking forward to being able to set TTLs via Dynamoose! Do you have an estimated completion time for 0.8.0?

**Comment by brandongoode** [comment]
I'm looking forward to it too.  No exact time on the release, but it will be as soon as I have time.  The more help with PRs and such the faster.  There are only a few remaining items.
