### ISSUE TITLE
Generated attributes: Pass current model to attribute default function.

### ISSUE THREAD

**Issue by vangorra** [automategreen/dynamoose#124]
It would be awesome if we could specify a default function for an attribute and get the current instance of the model as a parameter. That would allow us to populate the secondary index in a better way.
```javascript
const schema = {
  _id: String,
  country: String,
  state: String,
  surName: String,
  surNameIndex: {
    index: {
      default: model => {
        return `${model.country}_${model.state}_${model.surName}`;
      }
    }
  }
}
```

Seems passing the model here would do the trick:
https://github.com/automategreen/dynamoose/blob/108fcaa91fc1785dc4d3623231f6b7a16f877dc4/lib/Attribute.js#L280

More generically however, having a forceDefault boolean for the attribute to ensure the default is applied every time would also be useful. This would ensure the secondary index data is properly updated when the data is persisted.

**Comment by brandongoode** [comment]
Passing the model sounds like a great idea.  Want to submit it as a PR?

Not sure I follow the forceDefault.  Would this overwrite the value with the default, regardless of if there's currently a value? 

Also, default would not be in the index.  It should be applied directly to the attribute:
```js
const schema = {
  _id: String,
  country: String,
  state: String,
  surName: String,
  surNameIndex: {
    index: true,
    default: model => {
      return `${model.country}_${model.state}_${model.surName}`;
    }
  }
}
```

**Comment by troyswanson** [comment]
Is the idea for the generated value be stored in the DynamoDB table?

**Comment by vangorra** [comment]
@troyswanson  Yes.

**Comment by troyswanson** [comment]
Would it be possible for something like https://github.com/automategreen/dynamoose/issues/120#issuecomment-293621445 to be included with this?

**Comment by vangorra** [comment]
That looks out of scope of what I'm trying to accomplish here.

**Comment by troyswanson** [comment]
Fair enough.
