### ISSUE TITLE
Create project website (w/ documentation)

### ISSUE THREAD

**Issue by troyswanson** [automategreen/dynamoose#126]
A lot of projects are using the Wiki section of the GitHub repo for documentation lately.

Given the power of this project and the potential reach it has, something that has more features (sidebars, links, etc) might make sense to take advantage of.

**Comment by brandongoode** [comment]
I've been wanting to move the documentation to its own GitHub Pages site, but just haven't had the time. I'll try over the next week, I'll go ahead and set up the structure and copy the current README.

**Comment by vangorra** [comment]
Woot! Looking forward to this!

**Comment by brandongoode** [comment]
I'm good with the two-step approach (README -> Wiki -> Jekyll), but I wouldn't mind going straight to the final jekyll site.

**Comment by brandongoode** [comment]
So, since I was thinking about this, I decided to go ahead and register a domain.

dynamoose.com is taken so what is everyone's thought about dynamoosejs.com?

**Comment by troyswanson** [comment]
Make it rain! 💵 💦

**Comment by vangorra** [comment]
Well put. Make it rain!

**Comment by brandongoode** [comment]
So is that endorsement of dynamoosejs.com?

**Comment by troyswanson** [comment]
Yes.

**Comment by brandongoode** [comment]
Done -- dynamoosejs.com is ours.  I'll work on getting the GitHub Pages setup with it.

**Comment by vangorra** [comment]
Yep

**Comment by brandongoode** [comment]
OK.  http://dynamoosejs.com now points to the GH page.  Now we just need some content.

**Comment by brandongoode** [comment]
As a placeholder, I just copied the readme over to the docs/index, but that's just temporary.

I wanted to take some time to brainstorm the new layout.

Here's what I'm thinking as a starting point.

Pages/Sections:
Index/Getting started
Configurations
Schemas
Models
Querys
Scans

Another option is to have a single page with a sidebar to sections.  This makes searching for something easier.

As far a the look and feel.  I like https://github.com/poole/hyde but haven't had time to look around.  Any suggestions?

**Comment by byronmejia** [comment]
Hey. So I've recently started using dynamoose and loving it.

Let me know how I can help out in anyway. Would love to help see this project grow.

**Comment by byronmejia** [comment]
Also more than happy to help with creating a CI/CD pipeline to create documentation and auto upload to S3.

We use jsdocs at work, but more than happy to hear some better suggestions?

**Comment by brandongoode** [comment]
@byronmejia -- Thanks offering to help.  I need all the help I can get.

We're in the process of moving the docs over to GitHub Pages.  I'm open to the pipeline option with jsdocs, but not sure how well it would work with GitHub Pages.  Plus, all the jsdoc comments would need to be added to the source.

**Comment by byronmejia** [comment]
@brandongoode Yeah. Totally get what you mean. A few communities have comments for days in their repos. I personally am on the fence with with comments throughout source.

Depends what direction you'd like to take with that. Advantages of separating all the technical writing from the source code is it allows you to be more in depth without worrying about bloating the source. Also: super friendly for first time GitHub users to contribute to the documentation. 😄 

I'll have a bit of an experiment with using GitHub pages and get back to you with the results soon.

**Comment by brandongoode** [comment]
So I've been playing with the website this week and have something halfway presentable.

Let me know what you think.

https://dynamoosejs.com/

**Comment by lengk** [comment]
@brandongoode Looks good! 

Missing docs on Schema.methods  and Schema.statics?

**Comment by troyswanson** [comment]
The website looks great! Closing this issue since it looks awesome. Nicely done. 👍
