### ISSUE TITLE
Implement BatchGet

### ISSUE THREAD

**Issue by blakebyrnes** [automategreen/dynamoose#13]
Would be really nice to have BatchGet available as a feature when reading multiple keys at once.

This is the API they're using at dynamite (for reference)

client.newBatchGetBuilder()
    .requestItems('user', [{'userId': 'userA', 'column': '@'}, {'userId': 'userB', 'column': '@'}])
    .requestItems('phones', [{'userId': 'userA', 'column': 'phone1'}, {'userId': 'userB', 'column': 'phone1'}])
    .execute()

**Comment by brandongoode** [comment]
@blakebyrnes - It's been on my todo list for a long time, but I just haven't had the time.

@ricardopinto has added the functionallity in his fork:
https://github.com/ricardopinto/dynamoose#modelbatchgetkeys-options-callback

If @ricardopinto does a PR, I would be happy to merge it.

**Comment by ricardopinto** [comment]
Hi! I've sent a PR with batch operations implemented. https://github.com/automategreen/dynamoose/pull/14

**Comment by brandongoode** [comment]
Thanks -- I'll merge it in shortly

**Comment by brandongoode** [comment]
I published npm version 0.4.0 with batch functionallity.

Special thanks to @ricardopinto & @khamasaki. They did all the work.
