### ISSUE TITLE
Dynamoose error on create 'name is undefined'

### ISSUE THREAD

**Issue by chrisrijos** [automategreen/dynamoose#131]
I am using version 0.7.0 of Dynamoose, When I invoke the create function from the Dynamoose model the library is returning the following error. I have tried just about everything and cannot seem to be pinpointing what is causing this. 

` <pre>TypeError: Cannot read property &#39;name&#39; of undefined
            <br> &nbsp; &nbsp;at NewModel.Model.put (/Users/chrisrijos/SideProjects/aircraft-api/node_modules/dynamoose/lib/Model.js:202:72)
            <br> &nbsp; &nbsp;at Function.Model.create (/Users/chrisrijos/SideProjects/aircraft-api/node_modules/dynamoose/lib/Model.js:247:16)
            <br> &nbsp; &nbsp;at Function.NewModel.create (/Users/chrisrijos/SideProjects/aircraft-api/node_modules/dynamoose/lib/Model.js:99:18)
            <br> &nbsp; &nbsp;at createAircraft (/Users/chrisrijos/SideProjects/aircraft-api/server/api/Aircraft/aircraft.controller/createAircraft/index.js:6:14)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/chrisrijos/SideProjects/aircraft-api/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at next (/Users/chrisrijos/SideProjects/aircraft-api/node_modules/express/lib/router/route.js:137:13)
            <br> &nbsp; &nbsp;at Route.dispatch (/Users/chrisrijos/SideProjects/aircraft-api/node_modules/express/lib/router/route.js:112:3)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/chrisrijos/SideProjects/aircraft-api/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at /Users/chrisrijos/SideProjects/aircraft-api/node_modules/express/lib/router/index.js:281:22
            <br> &nbsp; &nbsp;at Function.process_params (/Users/chrisrijos/SideProjects/aircraft-api/node_modules/express/lib/router/index.js:335:12)
        </pre>`

**Comment by brandongoode** [comment]
@chrisrijos Can you share your Schema?

**Comment by chrisrijos** [comment]
`'use strict';

  var AWS = require('aws-sdk');
  var dynamoose = require('dynamoose');
  var chalk = require('chalk');
  
  var AircraftSchema = dynamoose.Schema({
    aircraftId: {
      type: Number,
      hashKey: true
    },
    model: {
      type: String,
      rangeKey: true,
      index: true,
      required: true
    },
    ownerId: {
      type: String,
      rangeKey: true,
      index: true,
      required: true
    },
    year: {
      type: String  
    },
    price: {
      type: Number,
      required: true
    },
    images: {
      type: [String] 
    },
    engine: {
      type: String
    },
    type: {
      type: String,
      required: true
    },
    address: {
      type: Object,  
      address_line: {
        type: String
      },
      state: {
        type: String
      },
      zip_code: {
        type: Number
      }
    },
    created: {
      type: Date
    },
    throughput: {
      read: 10,
      write: 10,
      timestamps: true
    }
  });

  const Aircraft = dynamoose.model('Aircraft', AircraftSchema); 

  module.exports = Aircraft; 
`

here is the schema @brandongoode

**Comment by joawan** [comment]
I experienced a similar thing. Fixed by rtfm, and `var AircraftSchema = new dynamoose.Schema({})`

**Comment by chrisrijos** [comment]
@joawan even leaving a blank schema is still giving me the same problem. The error appers when CRUD functions are invoked from Dynamoose models.

**Comment by joawan** [comment]
Yes, I had the same thing. It was due not having `new dynamoose.Schema({...})` and looking at the schema you provided, you are also missing `new`.

**Comment by chrisrijos** [comment]
@joawan you were correct, sorry I overlooked it. Thank you, issue should be closed, this was support related and not an issue.
