### ISSUE TITLE
Sample.js not working for AWS account.

### ISSUE THREAD

**Issue by rspl1006** [automategreen/dynamoose#132]
I have run sample.js but it didn't create table and items in dynamodb table of my aws account

**Comment by brandongoode** [comment]
Make sure your AWS credentials are set properly as environment variables. 

AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_DEFAULT_REGION must be set.

**Comment by rspl1006** [comment]
Thanks it's working fine now, 
Issue was region was wrong.

Thanks again for your quick reply.
