### ISSUE TITLE
Get all records

### ISSUE THREAD

**Issue by rspl1006** [automategreen/dynamoose#133]
How can I get all records using this component?

var TableNameSchema = new Schema({
  id: {
    type: String, 
    KeyType: "HASH"
  },
  field_4: {
    type: String,
    trim: true,
    required: true,KeyType: "RANGE"
    
  },
  created_at: {
    type: Date,
    default: Date.now
  },
  updated_at: {
    type: Date,
    default: Date.now
  },
  user: {
    type: Schema.ObjectId,
    ref: 'User',
    required: true
  },
  field_1: {
    type: String,
    trim: true,
    required: true
  },
  field_2: {
    type: String,
    trim: true,
    required: true
  },
  field_3: {
    type: String,
    trim: true,
    required: true
  }
});

TableName.query('user').eq(String(userId)).attributes(['id', 'field_1','field_2']).exec(function (err, devices) {
        if (err) {
        } else {
            res.jsonp(devices);
        }
    });

This give error 
"**Sorry we have a problem finding all devicesValidationException: Query condition missed key schema element: id**"

**Comment by brandongoode** [comment]
Query requires a Key and is only for getting a subset of items.  Use `TableName.scan().exec(...)`

**Comment by rspl1006** [comment]
Thanks, it's working fine.
But If I want to scan by user= userID then how can I do using scan function.

**Comment by rspl1006** [comment]
TableName.scan('user').contains(req.body.userID).exec(function (err, data) {
});

Using this it's working fine.

Thank you Brandongoode.
