### ISSUE TITLE
[Feature Request] AWS X-Ray support

### ISSUE THREAD

**Issue by gmadole** [automategreen/dynamoose#144]

**Comment by brandongoode** [comment]
It may work now.
 
Try this:

```js
var AWSXRay = require('aws-xray-sdk');
var dynamoose = require('dynamoose');
dynamoose.AWS = AWSXRay.captureAWS(require('aws-sdk'));
```

**Comment by brandongoode** [comment]
@gmadole Did this work for you?

**Comment by rnowosielski** [comment]
It did work for me.

**Comment by gmadole** [comment]
@rnowosielski  Sounds promising!

@brandongoode My first attempt a couple months ago didn't work but it's likely because I'm doing something else strange. I haven't gotten back to it since then. I'll retry with a simpler environment.

**Comment by brandongoode** [comment]
@rnowosielski - Thanks for the confirmation.

**Comment by MartinCerny-awin** [comment]
In version 2.7.0. We need to change dynamoose.aws.sdk

```
dynamoose.aws.sdk = AWS;
```
