### ISSUE TITLE
Nested property validation

### ISSUE THREAD

**Issue by jderose9** [automategreen/dynamoose#152]
There is not currently any way to describe schema for nested objects or arrays of child objects, correct?

Something like:
```
dynamoose.model(<name>, {
	parent: { 
		type:  [{
			childField1: { type: 'String' },
			childField2: { type: 'String' } 
		}]
	}
}
```

Thanks!

**Comment by brandongoode** [comment]
It's supported, but you'll need to set `useDocumentTypes` to `true`.  There's no example in the docs (PR anyone?), but here's an example from the tests.

https://github.com/automategreen/dynamoose/blob/92994f17df68cb3a190cb84b7a97706403f841a4/test/Schema.js#L298-L343

**Comment by jderose9** [comment]
Awesome, thank you!
