### ISSUE TITLE
New Attributes not getting update to the table.

### ISSUE THREAD

**Issue by mohamednizar** [automategreen/dynamoose#154]
I have a schema defined in the model, I added new fields to the schema, but on create or update the values are not getting saved.
```
'use strict';

var crypto = require('crypto');
var dynamoose = require('../../config/database');

var Schema = dynamoose.Schema; 

var ServiceGroupSchema = new Schema({ 
  client_id: {
    type: String,
    hashKey: true
  },
  code: String,
  active: Boolean,
  description:String,  
  name: String,
  picture:String,
  service_obj:{},
  deletedAt:Number,
},{timestamps:true});
 
module.exports = dynamoose.model('Service_Group', ServiceGroupSchema);

```
In this schema deletedAt and timestamps are newly added.Find my dynamoss default values.
`dynamoose.setDefaults({ create: true, update: true, waitForActive: true, });`

What is the issue with this ?

**Comment by brandongoode** [comment]
Are you using the current git repo or npm?  There are several improvements to timestamp updating that in the repo but not in the current version on npm (0.7).

Can you share some code where you're performing the updates to the model?

**Comment by mohamednizar** [comment]
This is working with the schema I created, but this one I updated the schema.I'm using  ` "dynamoose ":"~0.6.0`.

I use to update using this query
```
exports.updateServiceGroup = function (req, res, next) {
    var serviceGroup = new ServiceGroup(req.body)
    ServiceGroup.query('code').eq(req.body.code).where('client_id').eq(req.headers.client).exec(function (err, group) {
        // return res.status(200).json({data:group}); 
        console.log(group)
        if (err) { return console.log(err); }
        if (group.length > 0) {
            var group = group[0];
            group.description = serviceGroup.description;
            group.name = serviceGroup.name;
            group.active = serviceGroup.active;
            group.picture = serviceGroup.picture;
            group.save(function (err) {
                if (err) {
                    console.log(err);
                    res.status(400).send(err);
                } else {
                    // user.name = JSON.parse(user.user_info).fname+" "+JSON.parse(user.user_info).lname;
                    // console.info(user);
                    console.log('------------updated')
                    console.log(group)
                    res.json(group);
                }
            });

        }
    });

}
```

**Comment by mohamednizar** [comment]
On thing to be concern that the object of the success message contains new attributes.

![responce](https://cloud.githubusercontent.com/assets/8711284/26713516/bcba14f0-478a-11e7-838b-d4fa52a8aba9.png)

But the not saved in the dynamoss and can't query on those new data.

Thanks,
Nizar

**Comment by brandongoode** [comment]
I think the issue with the timestamp is your dynamoose version.  Can you try testing with the latest updates:

```json
"dependencies": {
  "package": "git://github.com/automategreen/dynamoose.git"
}
```

In your example code, I don't see deletedAt being set.

**Comment by brandongoode** [comment]
This should now work with v0.8.0
