### ISSUE TITLE
Model db access methods don't have a catch on the waitForActive() method

### ISSUE THREAD

**Issue by asue** [automategreen/dynamoose#157]
There doesn't seem to be a catch on the waitForActive on an access method, for example line 403 of Model.js when doing a get on a table.  The scenario is that the table does not exist so the waitForActive eventually throws an exception after its timeout, but it never bubbles up since it only has the then.

Suggest catching and rejecting it like
newModel$.table.waitForActive().then(get).catch(deferred.reject);

This is also across other operations such as put and delete.

**Comment by brandongoode** [comment]
Closed by #161
