### ISSUE TITLE
Query.in() not working as expected

### ISSUE THREAD

**Issue by Gregoirevda** [automategreen/dynamoose#160]
Knowing that the id is the HASH key, why doesn't this query work?

Model.query('id').in(ids).exec((err, hackEventDays) => {
}

**Comment by brandongoode** [comment]
@Gregoirevda You'll need to use `.scan` instead of `.query` for your example.

**Comment by Gregoirevda** [comment]
Thank you for your response.

Is this part of the documentation still correct then? 
https://dynamoosejs.com/api#scaninvalues

**Comment by brandongoode** [comment]
Yes, the documentation is correct, but it's referring to a query filter.  All queries require an `eq` with the hash key value.

The documentation isn't very clear about that.  I'll add updating the documentation to the todo list.
