### ISSUE TITLE
Searching in objects as a string

### ISSUE THREAD

**Issue by Mayhem93** [automategreen/dynamoose#162]
So I have a field as *Object* in dynamoose schema (which eventually translates to a json string in dynamoDB) and I tried to scan with a filter after this field like so `Model.scan('objectTypeFieldName').contains('acct').exec()` 

I know for sure my DB has items satisfying that filter (I also did the filter on the aws dynamodb dashboard and it's fine).

**Comment by brandongoode** [comment]
That's a limitation of dynamoose.  It's converting `'acct'` into a JSON object. So DynamoDB is searching for `'"acct"'`.   There's a PR under development right now that could be used to address this issue, #158.  Once it is implemented v0.8, the next release, will support the following:

```js
Model.scan({
  FilterExpression: 'contains(objectTypeFieldName, :val)',
  ExpressionAttributeValues: { ':val': 'acct' }
}).exec()
```

**Comment by Mayhem93** [comment]
@brandongoode Thanks !

**Comment by brandongoode** [comment]
@Mayhem93 Would you mind trying this with the master branch.  #158 has been merged into master.

**Comment by Mayhem93** [comment]
@brandongoode Don't think I can very, I'm pretty busy with other stuff and I used a imperfect workaround for this. Will let you know once I get a chance to test.

**Comment by brandongoode** [comment]
release v0.8.0 should now support this
