### ISSUE TITLE
Convert scan.eq('') to scan.null()

### ISSUE THREAD

**Issue by kiyonori-matsumoto** [automategreen/dynamoose#163]
Hi, 
I'm using latest master version of dynamoose. (#be6f662afbe9f4ef55cbf818df2d23d70198a24f)
When I execute following scripts, a typeerror has occurred.
```
TypeError: next is not a function
    at ./node_modules/dynamoose/lib/Scan.js:245:7
    ...
```

Please fix this if you can.

```javascript
process.env.AWS_REGION="us-east-1"
const dynamoose = require('dynamoose')

dynamoose.local()

const Schema = new dynamoose.Schema({
  id: { type: String, hashKey: true },
  email: { type: String },
})

const AAAA = dynamoose.model('AAAA', Schema)

AAAA.scan('email').eq("").exec().then(console.log, console.log) // error throwed

```

**Comment by brandongoode** [comment]
Attribute values cannot be blank strings in DynamoDB.

Try using the following scan:

```
AAAA.scan('email').null().exec().then(console.log, console.log)
```

**Comment by kiyonori-matsumoto** [comment]
@brandongoode 
Thanks for your reviewing.
It works well, so, if I want to compare an attribute to local variables, should I have to check that the local variables is not empty string before I issue a scan query?

**Comment by brandongoode** [comment]
@kiyonori-matsumoto  I agree it is redundant. `scan.eq('')` automatically be converted to `scan.null()`.
