### ISSUE TITLE
Add non existing element to array using dynamoose?

### ISSUE THREAD

**Issue by sabreenakp** [automategreen/dynamoose#168]
HI,   How to add to an array such that not inserting any  existing element?
Could you please provide an example?

**Comment by brandongoode** [comment]
You can use `batchPut` with `overwrite` set to false:

https://dynamoosejs.com/api#modelbatchputitems-options-callback

```js
Model.batchPut([item1, item2, item3], { overwrite: false })
```

**Comment by sabreenakp** [comment]
@brandongoode thanks for the reply!

How to write batchPut inside an update??                                                                                                                                                 

this.update({itemId:id, activeFlag:true},{ $PUT: { friends:newFriends } }, function(err,res) {
        if(err) {
            cb(err, res);
        }
        else{
            cb(err, res);
        }
    });

above shown is my query i need to add new friends to friends field in my schema , add non existing new friends to the friends array in the item matching itemId:id

i want to update a single item at a time.  not the all items in the table.

**Comment by brandongoode** [comment]
@sabreenakp  - where you able to get this working?
