### ISSUE TITLE
Add nested JSON support via update expressions.

### ISSUE THREAD

**Issue by benjcooley** [automategreen/dynamoose#17]
The current implementation uses the old API to support modifying attributes only at the top level (which is perfectly fine for the most part).

DynamoDB however has supported full nested JSON data structures in addition to update expressions that could arbitrarily modify data at any depth of the attribute tree.

For certain scenarios supporting nested structure modification can avoid the overhead of any locking for supporting certain types of dependent cross table data updates.

**Comment by brandongoode** [comment]
I haven't had time to really look into the details of using the newer nested structures. Most of my tables were created prior to the JSON data structures being supported. I'll have to take some time to understand the differences.

**Comment by brandongoode** [comment]
Tracking in #165
