### ISSUE TITLE
.scan parse error saveUnknown

### ISSUE THREAD

**Issue by fishcharlie** [automategreen/dynamoose#170]
I'm trying to get Dynamoose to scan and return all items without really defining a schema. I don't really want to define a schema because I'm using this code in another application that is a secondary application.

At first I had the following code:

	// define the schema for our model
	var theSchema = new dynamoose.Schema({}, { saveUnknown: true });
	// create the model for projects and expose it to our app
	var model = dynamoose.model('mytablea', theSchema);

That produced an error that said `TypeError: Cannot read property 'name' of undefined`.

Then just to test things I tried to change `theSchema` to the following:

	// define the schema for our model
	var theSchema = new dynamoose.Schema({_id: String}, { saveUnknown: true });

That produced an error that said `SyntaxError: Unexpected token F in JSON at position 0`.

The second time it actually called the `exec` function with that error. First time Dynamoose just throw that error and didn't even call that `exec` function.

Any ideas on how to fix this?

**Comment by brandongoode** [comment]
I've never tried that before.  I'll at least need to define the index key as it will check the table for the keys.

Could you create a failing test case and issue a PR with the test case?

**Comment by fishcharlie** [comment]
@brandongoode I can't seem to reproduce it when building a new test case. I did figure out right before line 428 in Attribute.js console.logging `val` prints an actual result from the database. So for example if I have an item in the table `{"key1":"test"}` `val` in this case = `test` I believe. And in my case `test` starts with `F` so that is why I'm getting that error. Still not totally sure why that is happening. Will keep doing some tests and see if I can learn more about it, and will post back here.

**Comment by fishcharlie** [comment]
Also on line 181 of Schema.js I added a console.log of `dynamoObj[name]` and in that case above results in `{ S: 'test' }`. Then on line 482 of Attribute.js `this.type.name` is = to 'object'. So it's almost like it's trying to parse an object when in reality it's a string.

**Comment by brandongoode** [comment]
What happens if you set `useDocumentTypes` to `true`?

```js
var schema = new Schema({...}, {
  useDocumentTypes: true
});
```

**Comment by fishcharlie** [comment]
@brandongoode Same thing.

    var theSchema = new dynamoose.Schema({_id: String}, { saveUnknown: true, useDocumentTypes: true });

**Comment by fishcharlie** [comment]
@brandongoode Any other ideas on this?

**Comment by fishcharlie** [comment]
So on [this line](https://github.com/automategreen/dynamoose/blob/master/lib/Attribute.js#L428) `transform` seems to be set to `JSON.parse`. `val` = `"Fish"` (since that is the value in the database). `json` = `{S: "Fish"}` and `type` = `"S"` and `attr` is undefined. So it's trying to do `JSON.parse` on `"Fish"` which isn't right at all. That's why it says `SyntaxError: Unexpected token F in JSON at position 0`

Not sure why this is happening...

**Comment by fishcharlie** [comment]
It also looks like [this line](https://github.com/automategreen/dynamoose/blob/92994f17df68cb3a190cb84b7a97706403f841a4/lib/Schema.js#L172) sets all `saveUnknown` attributes to be an Object type, *even* if the data type isn't an Object in the table. @cbarrese any thoughts on this? Looks like you did the pull request and wrote this code for `saveUnknown`. This really shouldn't default to an object, as there are a lot of object types Dynamoose and DynamoDB support other than objects (such as strings in this case).

Somehow Dynamoose needs to determine what type the data is and use that type.

Could be totally off base here. But looking through the code is leading me to this as the problem.

**Comment by brandongoode** [comment]
@fishcharlie -- I agree.  

The issue is with the saveUnknown defaulting to an Object for parsing:
https://github.com/automategreen/dynamoose/blob/324c8faa57ed10f752bed008467b5eb5fd979da2/lib/Schema.js#L172

When coverting to a DynamoDB object it checks object's type:
https://github.com/automategreen/dynamoose/blob/324c8faa57ed10f752bed008467b5eb5fd979da2/lib/Schema.js#L142

We should inspect the DynamoDB object to determing the best type.

**Comment by fishcharlie** [comment]
@brandongoode So would changing [this line](https://github.com/automategreen/dynamoose/blob/324c8faa57ed10f752bed008467b5eb5fd979da2/lib/Schema.js#L172) from `attr = Attribute.create(this, name, Object);` to `attr = Attribute.create(this, name, typeof model[name]);` fix it, you think? If so I can quickly make a pull request and submit it.

**Comment by fishcharlie** [comment]
@brandongoode This feature should get corrected before 0.8 if possible. I expected it to be more complicated than just changing what I mentioned above, but maybe not...

**Comment by brandongoode** [comment]
`model[name]` would be undefined.  We need to look at the `dynamoObj[name]` type.

I agree -- I'll make sure it's in 0.8.

**Comment by fishcharlie** [comment]
@brandongoode Awesome. Let me know if there is anything I can do to help. Not sure how much I can help out, as I don't really know how we could even start to get that type since it's not really stored anywhere. But really looking forward to this feature!! Will be super helpful in the current project I'm working on. So thank you very much!!!

**Comment by brandongoode** [comment]
@fishcharlie  Just pushed the changes.  Let me now if that fixes your issue.

**Comment by fishcharlie** [comment]
@brandongoode Thank you so much!! I’m currently away from my computer. Should be able to test hopefully within the next hour or so. Will let you know!

**Comment by fishcharlie** [comment]
@brandongoode Looks like this works to some extent. Now getting `Unexpected token o in JSON at position 1`. I'm using a NPM package to debug using a Electron. I have attached the point that I just debugged right before it threw that error.

<img width="761" alt="screen shot 2017-07-02 at 3 33 08 pm" src="https://user-images.githubusercontent.com/860375/27773982-e7dc9a40-5f3b-11e7-8b81-5106a5be94e2.png">

Not sure why that would have anything to do with `Unexpected token o in JSON at position 1`. And honestly I could be looking in the wrong place. But right once I click continue after that breakpoint it throws that error.

At least it's different than the first one haha, so making progress.

**Comment by fishcharlie** [comment]
@brandongoode This was a problem in my database. I had a string `1` (which you might be able to gather from the image above. But this still seems like an edge case Dynamoose should (hopefully) be able to handle.

**Comment by brandongoode** [comment]
@fishcharlie  - It should handle the number string.  I added one to the test case:
https://github.com/automategreen/dynamoose/blob/master/test/Schema.js#L791

**Comment by fishcharlie** [comment]
@brandongoode Hmm. No idea why that was causing problems. It's strange it was a JSON error also. But changing it to a number in DynamoDB fixed it. Thanks so much!

**Comment by brandongoode** [comment]
OK - I think I know what happened.  At some point in time, it gets set as a number in dynamoose.  Because it's a number it looks for the "N" attribute which doesn't exist because it is a string, "S".

**Comment by fishcharlie** [comment]
@brandongoode Any ideas on how to fix or?

**Comment by brandongoode** [comment]
For the processing of the unknown attributes to work, all the values for an attribute in the table must be consistent. 

I'm assuming some of the values for the attribute were typed as String and some were typed as a Number in DynamoDB.

I'm not really sure how to handle this.

**Comment by fishcharlie** [comment]
@brandongoode Yeah, everything was a string but one item had it accidentally as a string. I don't know the code base well enough to really advise here. But I'd say it's a really strange edge case (not sure how many databases have this in real world practice, but guessing pretty few).

**Comment by brandongoode** [comment]
I think I'll leave alone for release 0.8 and see if any other have the same issue.

**Comment by fishcharlie** [comment]
@brandongoode Now that this is taken care of will 0.8 be released this week then?
