### ISSUE TITLE
Getting model with range key with false-y value fails

### ISSUE THREAD

**Issue by sethsamuel** [automategreen/dynamoose#177]
Trying to get a model with range key 0 was failing with the message `Range key required`. The culprit is this line:
https://github.com/automategreen/dynamoose/blob/50ccb8ea8e324bf62469bc32ab2562c3dc3ed894/lib/Model.js#L350

which does a false-y check rather than an actual existence check.

**Comment by brandongoode** [comment]
@sethsamuel  - Thanks - Want to create a PR?
