### ISSUE TITLE
Model.get nested value

### ISSUE THREAD

**Issue by Xavier-IV** [automategreen/dynamoose#180]
I'm using PassportJS that is using this schema:

    local: {
      email: String,
      password: String
    },
    facebook: {
      id: String,
      token: String,
      email: String,
      name: String
    },
    // the rest is almost identical.

In PassportJS, I need to find this value to verify that an e-mail does not exist

      User.get({'local.email': someRetrievedEmailValue}, function (err, user) {
          // Some simple logic here
      }

Or maybe I can replace those with a param variable like this.
```
let params = {
   local: {
      email: someRetrievedEmailValue
   }
}
User.get(params, function (err, user) {
    // Some simple logic here
}
```
I want to retrieve the `email` that is nested inside `local` Is there any  solution or workaround for this? Since most of implementation by Passport will require to get nested parameter.

Here is a reference on [Scotch.io](https://scotch.io/tutorials/easy-node-authentication-setup-and-local). Everything is working fine, and I can insert some registration datas to DynamoDB, only that when it comes to searching nested params, I'm stucked.

Thanks in advance.

**Comment by brandongoode** [comment]
You'll need to use scan to search for nested values.

```js
var filter = {
  FilterExpression: 'local.email = :email',
  ExpressionAttributeValues: {
    ':email': someRetrievedEmailValue
  }
};

User.scan(filter).exec()
  .then(function(user) {
    console.log(user);
  })
  .catch(function(err) {
    console.error(err);
  });
```

**Comment by hunghkit** [comment]
do you know how to query or scan data with Array type, @brandongoode?
Example data
"Order": {
 "Items": [{
    "name": "product 1",
  }, {
    "name": "product 2",
 }]
}

**Comment by dimitribocquet** [comment]
Hi, I'm using PassportJS too, and I have a problem with scan function and filter.

Here is my model :

```
	id: {
		type: String,
		hashKey: true,
		default: function(){
			var flakeId = new FlakeId();
			return intformat(flakeId.next(), 'dec');
		}
	},
	facebook: {
		id: {
			type: Number,
			required: false,
		},
		name: {
			type: String,
			required: false,
		},
	},
```

In DB I've got that in facebook attribute :
```
{"id":"1041244171637XXXX","name":"Dimitri Bocquet"}
```

And I do that :

```
      var filter = {
        FilterExpression: 'facebook.id = :profileId',
        ExpressionAttributeValues: {
          ':profileId': profile.id
        }
      };

      User.scan(filter)
        .limit(1)
        .exec()
        .then(function(users){
          console.log('callback users scan', users.length);
        })
        ...
```

I have 0 results. Of course I have the user in my DB, with this value. I've tried to hard code the value (`':profileId': '1041244171637XXXX'`) just for testing but I have any results. Then I've tried with `id` attribute instead of `facebook.id` in the filter and it works. So I don't know why it's not working with `facebook.id` attribute.

Thanks !

**Comment by hunghkit** [comment]
you need to add useDocumentTypes: true in define schema, @dimitribocquet

**Comment by dimitribocquet** [comment]
@hunghkit It's working! Thanks a lot!

**Comment by rawsh** [comment]
@brandongoode Just tried that:

```
var filter = {
                  FilterExpression: 'local.email = :email',
                  ExpressionAttributeValues: {
                    ':email': email
                  }
                };
                User.scan(filter).exec()
                    .then(function(user) {
                        if (user) {
                            return done(null, false, req.flash('signupMessage', 'That email is already taken.'));
                        } else {
    
                            // create the user
                            var newUser            = new User();
    
                            newUser.local.email    = email;
                            newUser.local.password = newUser.generateHash(password);
    
                            newUser.save(function(err) {
                                if (err)
                                    return done(err);
    
                                return done(null, newUser);
                            });
                        }
                    })
                    .catch(function(err) {
                        return done(err);
                    });
```

ValidationException: Invalid FilterExpression: Attribute name is a reserved keyword; reserved keyword: local

**Comment by fishcharlie** [comment]
@rawsh To me that error means that you have to call it something other than `local`. See [this article for reserved keywords](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html).

**Comment by rawsh** [comment]
@fishcharlie Aha, setting it to "plain" fixes the issue.

Looks like there is limited support for nested schemas? What's an alternative to 

```
var newUser            = new User();
                        
                        console.log(newUser);

                        newUser.plain.email    = email;
                        newUser.plain.password = newUser.generateHash(password);
```

**Comment by fishcharlie** [comment]
@rawsh See issue #301 and PR #329 for more info on nested schemas. Personally I haven't played around with nested schemas a lot. It's something I would like to get better documented and improve support for. In all my schemas I just keep everything at the top level.

**Comment by meszaros-lajos-gyorgy** [comment]
Just a sidenote:

If your schema looks like the following

```javascript
const UserSchema = new dynamoose.Schema({
  id: String,
  accounts: {
    local: Object,
    facebook: Object,
    google: Object
  }
})

const UserModel = dynamoose.model('User', UserSchema)
```

and `accounts.facebook` will get whatever key/value pairs passport returns - but guaranteed to have id among the keys - then the `FilterExpression` will not give back any results.

```javascript
const nestedQuery = (pathString, value, model) =>
  model
    .scan({
      FilterExpression: `${pathString} = :val`,
      ExpressionAttributeValues: {
        ':val': value
      }
    })
    .exec()

const findUserByFacebookId = facebookId => {
  return nestedQuery('accounts.facebook.id', facebookId, UserModel).then(users => {
    return users.length === 0 ? null : users[0]
  })
}
```
