### ISSUE TITLE
indexes are not synchronized and update flag is set to false

### ISSUE THREAD

**Issue by cekimy** [automategreen/dynamoose#183]
Hi, i put my dynamodb from local to aws, but i got this error "indexes are not synchronized and update flag is set to false"
It's the error which is only thrown by dynamoose, so i can't google any information.
How to solve this problem?
Thanks! 
(Sorry for my pool english)

**Comment by cekimy** [comment]
i console table.options and indexes at
```
if (indexes.delete.length > 0 || indexes.create.length > 0) {
    debug('indexes are not synchronized and update flag is set to false');
    deferred.reject('indexes are not synchronized and update flag is set to false');
}
```
the output is
```
{ create: true,
  waitForActive: true,
  waitForActiveTimeout: 180000,
  prefix: '' } 

{ delete: 
   [ { IndexName: 'xx_id-index',
       KeySchema: [Object],
       Projection: [Object],
       IndexStatus: 'ACTIVE',
       ProvisionedThroughput: [Object],
       IndexSizeBytes: 0,
       ItemCount: 0,
       IndexArn: 'arn:aws-cn:dynamodb:cn-north-1:xxxx:table/xxxx/index/xx_id-index' } ],
  create: 
   [ { IndexName: 'xx_idGlobalIndex',
       KeySchema: [Object],
       ProvisionedThroughput: [Object],
       Projection: [Object] } ],
  both: [] }
```

**Comment by lrcry** [comment]
Can you please check your model definition?

As far as I know, `update` flag in model definition is where to expect.

Please refer to [this](https://dynamoosejs.com/api#dynamoosemodelname-schema-options). If you would like to allow the update of table structures (e.g. indexes, etc.), you need to set it to `true`.

**Comment by cekimy** [comment]
thank you @lrcry , it's ok now

**Comment by lrcry** [comment]
No worries. Glad I could help ;) @cekimy

**Comment by jignesh248** [comment]
I am working locally with dynamoDB, I have **update flag set to true**, and just **added a new index( to an existing filed ).**
Now I am getting error "Indexes are not synchronized and update flag is set to false". Any of you facing the same issue.
