### ISSUE TITLE
Data Storage in String Format For Object/Array/Map/List All Cases

### ISSUE THREAD

**Issue by bansaldeepak** [automategreen/dynamoose#184]
Hi Team, 

Want to bring to your notice that what ever type we choose in schema it stores data in string after stringify. Please fix this issue so that we can store this in desired format.

**Comment by brandongoode** [comment]
Use `useNativeBooleans` and `useDocumentTypes` to change the DynamoDB types.

**Comment by bansaldeepak** [comment]
@brandongoode Thanks for your reply. I tried with same before reporting issue. But it didn't work for me. Its stringify all the Arrays & Objects. If i am not wrong then in code for all Object, Map, List, Array **dynamofy: JSON.stringify** .

**Comment by brandongoode** [comment]
@bansaldeepak Can you provide your Schema?  Are you defining the nested object?  Known nested objects will be converted to JSON strings. Is your issue the same as #146?

**Comment by bansaldeepak** [comment]
@brandongoode Please check my schema below.

```
{
	APPLICATION_ID: {
		type: String,
		hashKey: true,
		required: true,
		trim: true
	},

	TASK_STATUS: {
		type: String,
		required: true,
		trim: true
	},
	
	TASK: {
		type: Object,
		required: true
	},
	
	USER_EMAIL: {
		type: String,
		trim: true
	}
},{
	throughput: 5,
	useDocumentTypes:true,
	timestamps: {
		createdAt: 'CREATED_AT',
		updatedAt: 'UPDATED_AT'
	}
}
```

**Comment by brandongoode** [comment]
@bansaldeepak, That's the same issue in #146.  It's on the todo list to add this functionality.
