### ISSUE TITLE
Promise : catch never called

### ISSUE THREAD

**Issue by dimitribocquet** [automategreen/dynamoose#186]
I'm trying to use [Model.save](https://dynamoosejs.com/api#modelputoptions-callback--modelsaveoptions-callback) (or [Model.create](https://dynamoosejs.com/api#modelcreateobject-options-callback)) and use a promise on it. But if a record is not saved, `catch` is not called, so I have any error.

Here is my code :

```
var example = new ExampleModel({...});

example.save({
	overwrite: false
})
.then(function(saved){
	console.log('model saved?',saved);
	res.json({"success":true,"message":"model saved!","model": saved});
})
.catch(function(err){
	console.log('model not saved',err);
	res.status(400).json({"success":false,"message":err});
});
```

Am I doing something wrong?

Thanks !

**Comment by brandongoode** [comment]
@dimitribocquet  -- Could you run this with DEBUG enabled?

**Comment by dimitribocquet** [comment]
Hmm, I can't reproduce the bug now. Maybe I did something wrong at this moment.

Thanks!
