### ISSUE TITLE
Error: Cannot do operations on a non-existent table

### ISSUE THREAD

**Issue by dimitribocquet** [automategreen/dynamoose#188]
Yesterday my code worked well, but now I have this error : 

> Cannot do operations on a non-existent table

Here is my schema :

```
var modelSchema = new Schema({
	test: {
		type: String
	},
	again: {
		type: String
	},
	last: {
		type: String
	},
}, {
	timestamps: true,
});
```

And here the debug file : 
[dynamoose.txt](https://github.com/automategreen/dynamoose/files/1197289/dynamoose.txt)

**Comment by brandongoode** [comment]
The error in the logs is just Dynamoose detecting that it should create a table.

**Comment by dimitribocquet** [comment]
Okay, I thought I had a bug because of that, but it was me! Thanks!
