### ISSUE TITLE
Suggestion: allow model.update() to be passed an object including hashkey

### ISSUE THREAD

**Issue by ro-savage** [automategreen/dynamoose#196]
[Dynogel](https://github.com/clarkie/dynogels) has a nice feature which uses the model to understand what is the `hashkey` is and update a table accordingly.

Take a database item that looks like
`{id :1, name: 'ro', location: 'australia'}`
with id as the `hashkey`

If you want to just change the location with dynogel you can just pass an object like
`{id: 1, location: 'united states'}`

```js
const personScheme = new Schema({
    id: {
      type: String,
      hashKey: true
    },
    name: String
    location: String
})

const personModel = dynamoose.model('person', personScheme);

```

**Dynogel's code**
```js
const newData = {id: 1, location: 'united states'}
personModel.update(newData, (err, data) => data)
```

**Dynamoose code**
```js
const newData = {id: 1, location: 'united states'}
const hashKey = newData.id
delete newData.id
personModel.update({id: hashKey}, newData, (err, data) => data)
```

In dynamoose it is required to seperate the haskey, and also remove it from the original update object. So it looks more like.

I believe it is a common pattern to pass an entire object including the key, and expect to ignore the id, and update/add any other fields.

Is this something you'd be interested in adding?

**Comment by brandongoode** [comment]
`.update` is targeted more for updating a single attribute without needing to send the whole object to DynamoDB. This keeps the write usage lower for larger objects.

If you have the whole object just use `.save()`;

```
const newData = new personModel({id: 1, location: 'united states'});
newData.save(newData, (err, data) => data);
```

That being said, I think to have the logic in `.update` extract the key is a great idea.  Dynamoose knows the hash and range keys and could easily remove them from the updated object.

**Comment by ro-savage** [comment]
So `update` in Dynogel you don't need to send the whole object. You can send one property, or three or every property. It doesn't overwrite, it just updates the fields contained and doesn't touch any that are missing.

I used the statics api you made to add my own method which does this. I am pretty busy at the moment, but I can take a look at adding your suggested enhancement if I get time (or feel free to do it, if you have time).

In the mean time, for anyone who needs something. This is what I am using. However please note, this is very naive and **Only works with a simple haskey as your primary key**. 

**This will not work if you have a haskey and range as your primary key**.

```js
mySchema.statics.edit = function(data) {
  const hashKeyName = mySchema.hashKey.name
  const hashKey = data[hashKeyName]

  if (!hashKey) {
    throw new Error(`Failed to edit table. Missing the hashkey (${hashKeyName}). Found ${JSON.stringify(data)}`)
  }

  delete data[hashKeyName]
  return myModel.update({[hashKeyName]: hashKey}, data).then(newData => newData)
}
```

**Comment by brandongoode** [comment]
Completely understand about the being busy.  I'll flag this for 0.9 and add it myself if no one else beats me to it.

**Comment by brandongoode** [comment]
Turns out its a pretty minor change to make this work so I'll go ahead and add it in 0.8.

**Comment by ro-savage** [comment]
@brandongoode - Can you please release this on NPM?

Thanks
