### ISSUE TITLE
In Model.put() / Model.save(), the returned promise is not rejected on error

### ISSUE THREAD

**Issue by AndreySoftware** [automategreen/dynamoose#197]
For example, if doing a conditional save that fails, the returned promise object is resolved instead of being rejected.
This happens because the following code returns the wrong promise:
`
if(model$.options.waitForActive) {
      return model$.table.waitForActive().then(putItem).catch(deferred.reject);
    }`

Suggested fix:
return `deferred.promise.nodeify(next)` instead.

**Comment by brandongoode** [comment]
Would you be willing to correct it in a PR?

**Comment by lennym** [comment]
I've just hit this same issue with `Model.create`. I'll put together a PR.

**Comment by lennym** [comment]
Ugh, just spent the last hour trying to recreate the issue with a failing test before I spotted that this has already been fixed at #200 :-(

Any chance of publishing a new version?

**Comment by jkrusinski** [comment]
A new version for this bug would be of great help for me as well!

**Comment by brandongoode** [comment]
@lennym  Sorry for not publishing an updated release and sorry for not getting back any sooner.  I've been slammed lately and some of my sided projects (i.e. this one have suffered).  I'll try to push out an updated version this week.

**Comment by brandongoode** [comment]
The fix is in 0.8.6
