### ISSUE TITLE
Scan only running parseDynamo on the first item

### ISSUE THREAD

**Issue by tsdorsey** [automategreen/dynamoose#199]
Things had been going swimmingly using serverless.com, lambda, api gateway, dynamodb and dynamoose. Between 3am and 10am PDT on the 30th of August my scan responses started to send back raw dynamodb JSON for all but the first item.  When I use the serverless invoke local functionality it parses all the items but the deployed functions on AWS Lambda only parse the first "Item".

I turned on debug on the lambda function and here is the relevant part of the output:

```
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:scan scan response { Items: 
[ { updatedAt: [Object],
createdAt: [Object],
group: [Object],
order: [Object],
id: [Object],
name: [Object],
type: [Object] },

...

{ updatedAt: [Object],
createdAt: [Object],
group: [Object],
order: [Object],
id: [Object],
name: [Object],
type: [Object] },
{ updatedAt: [Object],
createdAt: [Object],
group: [Object],
order: [Object],
id: [Object],
name: [Object],
type: [Object] },
{ createdAt: [Object],
order: [Object],
id: [Object],
name: [Object],
updatedAt: [Object],
type: [Object] } ],
Count: 45,
ScannedCount: 45 }
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:model applying virtuals
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parsing date from 1504081581097
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parseDynamo: updatedAt : "date" : "2017-08-30T08:26:21.097Z"
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parsing date from 1504081581097
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parseDynamo: createdAt : "date" : "2017-08-30T08:26:21.097Z"
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parseDynamo: group : "string" : "Movement"
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parseDynamo: order : "number" : 30000
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parseDynamo: id : "number" : 4200
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parseDynamo: name : "string" : "Smooth"
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:attribute parseDynamo: type : "string" : "Camera"
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:schema parseDynamo:
{
    "updatedAt": "2017-08-30T08:26:21.097Z",
    "createdAt": "2017-08-30T08:26:21.097Z",
    "group": "Movement",
    "order": 30000,
    "id": 4200,
    "name": "Smooth",
    "type": "Camera"
}

Wed, 30 Aug 2017 17:43:22 GMT dynamoose:scan scan parsed model NewModel {
updatedAt: 2017-08-30T08:26:21.097Z,
createdAt: 2017-08-30T08:26:21.097Z,
group: 'Movement',
order: 30000,
id: 4200,
name: 'Smooth',
type: 'Camera' }
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:model applying virtuals
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:scan scan parsed model NewModel {
updatedAt: { N: '1504081581097' },
createdAt: { N: '1504081581097' },
group: { S: 'Framing' },
order: { N: '20000' },
id: { N: '3700' },
name: { S: 'Medium' },
type: { S: 'Camera' } }
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:model applying virtuals
Wed, 30 Aug 2017 17:43:22 GMT dynamoose:scan scan parsed model NewModel {
createdAt: { N: '1504081581097' },
order: { N: '50000' },
id: { N: '2200' },
name: { S: 'Dark' },
updatedAt: { N: '1504081581097' },
type: { S: 'Emotion' } }

...

END RequestId: b6ede485-8daa-11e7-8f68-57777830a467
```

As you can see the debug calls to `dynamoose:attribute parseDynamo` `dynamoose:schema` do not happen for Items 1 - N.

Here was my scan code:
```
  Tag.scan()
    .all()
    .exec()
    .then(result => callback(null, success(result)))
    .catch(err => callback(null, failure(err, { status: false })));
```

I mangled it to do the conversion manually and got the response I expected. All JSON converted to normal objects. Here is that code:
```
  Tag.scan()
    .all()
    .exec()
    .then(result => {
      result = result.map(item => {
        const t = new Tag();
        t.$__.schema.parseDynamo(t, item);
        return t;
      });
      callback(null, success(result));
    })
    .catch(err => callback(null, failure(err, { status: false })));
```

I'm at a loss as to why this is happening, the code makes sense (both mine and yours). I think I'm going to have to hack in my parsing for now and move on. Hope we can find a solution.

-Trevor

**Comment by tsdorsey** [comment]
Ok, so I rolled my API code back 2 revisions and tried it. Still the same issue. Here is a network request from my app in Chrome.

```
[
  0: {
  createdAt: "2017-08-30T08:26:21.097Z"
  id: 4200
  name: "Smooth"
  updatedAt: "2017-08-30T08:26:21.097Z"
  }
  1: { 
  createdAt: {N: "1504081581097"}
  group: {S: "Framing"}
  id: {N: "3700"}
  name: {S: "Medium"}
  order: {N: "20000"}
  type: {S: "Camera"}
  updatedAt: {N: "1504081581097" }
  }
  ...
]
```

As you can see, the second item has attributes that I added at a later date like `group`, and `order`. If you look in the DynamoDB table the first item (id: 4200) has those attributes as well but because it's been parsed by the schema they were filtered out.

**Comment by jasonlbloom** [comment]
I'm also seeing this in 0.8.4 but works properly in 0.8.3.

**Comment by tsdorsey** [comment]
I'm on 0.8.3.  So frustrating. I've spent the last 6 hours trying to figure out why.

**Comment by tsdorsey** [comment]
Even worse is that it worked when I went to bed and didn't work when I woke up. I'm pretty sure I didn't change anything while I was asleep which leads me to think something was updated on the DynomoDB end but there's no info about it.

**Comment by tsdorsey** [comment]
Solved.

I had `"dynamoose": "^0.8.3"`, in my package.json. So many nasty things in my head right now. That @#$% little *&%$# `^` symbol. During the serverless deploy it must grab the latest versions of everything it can because I just checked and the compiled package being sent to AWS Lambda was 0.8.4. Locally I'm still on 0.8.3 so when I invoke locally everything works just fine. 

😡 6 F-ing hours over this.... no words.

**Comment by jasonlbloom** [comment]
Hmm, it is definitely working for us on 0.8.3. Try making sure you're definitely using 0.8.3. I realized I had "^0.8.3" in my package.json and 0.8.4 was getting installed. Changed package.json to "0.8.3".

**Comment by tsdorsey** [comment]
Yes, sorry, still getting over my frustration. I have since removed the `^` from my package.json file and all is well now.

**Comment by tsdorsey** [comment]
I can confirm this is bug in version `0.8.4`

**Comment by tsdorsey** [comment]
Moral of the story is to NEVER EVER allow your package manager to pick the version. Lock it down 100% and only make changes when you decide to. I have just finished doing that with this project and will remember to do so for the rest of my days.

**Comment by tsdorsey** [comment]
My apologies to @brandongoode for cluttering up this bug report my rants.

**Comment by brandongoode** [comment]
@tsdorsey Sorry about the bug -- no need to apologize.  Let me see if I can figure out what broke.

**Comment by tsdorsey** [comment]
@brandongoode I would also suggest taking down the 0.8.4 release on npm.

**Comment by brandongoode** [comment]
unpublish was the first thing I did -- About to push 0.8.5 without the map error

**Comment by dmitrirussu** [comment]
Hi guys you can solve your issue using AWS-SDK... dynamoose does not have deep parse for your json...
```
{
payload: {
     type: Map,
     required: false,
     toDynamo: AWS.DynamoDB.Converter.input,
     fromDynamo: AWS.DynamoDB.Converter.output,
 }
}
```

**Comment by fishcharlie** [comment]
@dmitrirussu I'm very confused about your question or problem. One thing that recently I figured out. If you are using `Map` or `List`. You have to pass in a `map` or `list` property. I also believe the types, `map` and `list` have to be strings.

See https://github.com/dynamoosejs/dynamoose/issues/230#issuecomment-361412970, for more information.

Also see #445, and #446.

Overall this is an area where the documentation is VERY poor. I'm still trying to wrap my head around it a bit more, then will work on updating the documentation.

Finally, you shouldn't need to set `toDynamo` and `fromDynamo` to the `AWS.DynamoDB.Converter`. Dynamoose handles that for you.
