### ISSUE TITLE
0.8 Change log relative to what version?

### ISSUE THREAD

**Issue by craigsketchley** [automategreen/dynamoose#206]
I'm looking to update our app from 0.4.1 to the current 0.8.5. The 0.8 change log seems harmless enough but what version was it relative to? Was there a 0.7? Just trying to get an idea of what might break if we upgrade from 0.4.1.

**Comment by brandongoode** [comment]
There was a 0.7 and 0.6 release (0.5 had an issue, and I removed it). I didn't do changelogs for them, but they shouldn't change any API's.  I have tried hard to make sure all releases are not breaking.

You'll have to look through the commits to see what changes were in 0.7: https://github.com/automategreen/dynamoose/commits/v0.7.0

**Comment by craigsketchley** [comment]
Perfect, thanks @brandongoode
