### ISSUE TITLE
Question: which branch should be used as the destination for PRs?

### ISSUE THREAD

**Issue by lovell** [automategreen/dynamoose#208]
Hello, when attempting to create a pull request I noticed there is no `master` or similar trunk-like branch in this repo (e.g. https://github.com/automategreen/dynamoose/branches generates a 500 error).

Should PRs be targeted at the `v0.9.0` branch?

**Comment by brandongoode** [comment]
If the PR is a completely new feature or break backward compatibility something use 0.9.  If it's a fix or a minor enhancement use master.   Not sure why you got the 500 error. 

Also, sorry for the slow response. I've been over-obligated and haven't had enough time.

**Comment by lovell** [comment]
Thanks Brandon, that makes sense. No need to apologise, this is open source and your time is precious.

It looks like when you pushed the `master` branch yesterday it "fixed" the 500 error from Github too, hooray!
