### ISSUE TITLE
How to initialize dynamoose?

### ISSUE THREAD

**Issue by spitfyr86** [automategreen/dynamoose#218]
I'm trying to connect to a local dynamoDB in my machine but I always get the error, "ConfigError: Missing region in config."
By the way, I'm using Typescipt in my Node.js app.

**Comment by brandongoode** [comment]
Try setting your env variable for the region (even though it's not really needed for local).
```sh
export AWS_REGION="us-east-1"
```

**Comment by jacintoArias** [comment]
Its seems to be the expected behaviour in `aws-sdk` aws/aws-sdk-js#880. By default it creates different database files for each region (unless specified)

Shall we close this one then?

**Comment by spitfyr86** [comment]
I didn't have time to resolve this. I'll get back on this if I can.
