### ISSUE TITLE
Support Atomic Counters in Update $SET

### ISSUE THREAD

**Issue by theparkland** [automategreen/dynamoose#22]
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.Modifying.html#Expressions.Modifying.UpdateExpressions.SET.IncrementAndDecrement

From what I can tell operations like `SET Price = Price - :p` are not supported.  Only `SET Price = :p`.

**Comment by brandongoode** [comment]
You are correct.  Would using the $ADD operator work? 
https://github.com/automategreen/dynamoose#modelupdatekey-update-callback.
