### ISSUE TITLE
Attribute type Map (and List) not working when retrieving data from DynamoDB

### ISSUE THREAD

**Issue by yurilausberg** [automategreen/dynamoose#231]
https://github.com/automategreen/dynamoose/blob/d4a3ad66329852fc5e400e961d75a027b90eb03d/lib/Attribute.js#L44

I'm noticing that when I'm debugging Attribute.js (line 43) for a `type.name === 'map'` that the value.map is undefined, causing the object not to get parsed.

If I skip the if statement on line 43, and don't reassign `value = value.map` (line 44), the code runs just fine.

Any ideas why this is happening?, I'm using Angular2 TypeScript with the following Schema Definition, and my role attribute will not get parsed upon a model.get(), unless I skip Line44:

     ` 
      var userSchema = new schema({
      displayName: { type: String },
      image: { type: String },
      email: { type: String },
      role: {type : { reader : Boolean, writer : Boolean, admin : Boolean}}
      },{
        useDocumentTypes: true,
        useNativeBooleans: true
      });
     `

Please assist?
Thanks much

**Comment by brandongoode** [comment]
With nested objects, Dynamoose doesn't need the type declared.  Try this:

```js
  var userSchema = new schema({
    displayName: { type: String },
    image: { type: String },
    email: { type: String },
    role: { reader : Boolean, writer : Boolean, admin : Boolean}
  },{
    useDocumentTypes: true,
    useNativeBooleans: true
  });
```
