### ISSUE TITLE
Is it possible to query unique values?

### ISSUE THREAD

**Issue by nicolascamilo** [automategreen/dynamoose#237]
Just like I would do with SQL, is there any SELECT UNIQUE "column_name" kind of function here? I can't find one.

Thanks!

**Comment by brandongoode** [comment]
Yes. Use `.attributes(...)`.

https://dynamoosejs.com/api#queryattributesattributes

**Comment by nicolascamilo** [comment]
But that will return unique values, right? 
I have a table like this:
```
Column 1 | Column 2 |
-----------------------
Beatles     |    3
Stones      |   4
Beatles     |   2
Beatles     |   1
Stones      |   4
The Who     |  1
```

The output will be something like this?
```
{
 "Beatles",
 "Stones",
 "The Who"
}
```

**Comment by brandongoode** [comment]
O -- my bad -- misread the question -- There is no way to get unique values from DynamoDB that I know of.

**Comment by nicolascamilo** [comment]
Oh! It's okay :) do you think that will be available in a future release?

**Comment by brandongoode** [comment]
That would be up to Amazon to implement.

**Comment by chuckcassie** [comment]
Depending on the language you are using, you could use your interface program to create an associative array (hash) using the column values as keys and assign some value to each key (eg. array{key} = 1). Then you just cycle through all your keys - if it exists then it is one of the values in your original list.
