### ISSUE TITLE
How can you mock the database calls?

### ISSUE THREAD

**Issue by jdcrecur** [automategreen/dynamoose#256]
Is it possible to mock the database calls with dynamoose? 

I have looked into using https://www.npmjs.com/package/aws-sdk-mock but without much joy.. is there a preferred method to mock?

**Comment by brandongoode** [comment]
What is your main goal?  You can use a local mock database the test: https://dynamoosejs.com/api#dynamooselocalurl

**Comment by fishcharlie** [comment]
Closing due to no reply. Please let us know if you are still having this issue and we can try to help further.

**Comment by Br0kensword** [comment]
So how does one go about mocking database calls from Dynamoose? I am trying to unit test a function that creates a user with the Model.create() function. How would I go about mocking that and returning a successful response so that my unit test passes?

**Comment by dolsem** [comment]
@Br0kensword One (not ideal) way to do testing is to use a local DynamoDB instance, which you can populate with a client like dynamon. However, I am myself curious about how to do actual request mocking.

**Comment by ckuiawa** [comment]
@brandongoode Using a local db is no longer really a unit test, it's more of an integration test. You also run the risk of setup data from one test effecting the results of other tests.  I know it's possible for that to happen anyway, but I would think the likelihood is greater when using a local database.

**Comment by jacktuck** [comment]
@ckuiawa is right. Has anyone had any success with Sinon for stubbing? I'm stuck trying to mock a model for a unit test (no local dynamo allowed).

```
const sandbox = sinon.createSandbox();

  sandbox
    .stub((dynamoose as any).models, modelName)
    .callsFake(() => {
      return {
        update: (args) => {
          t.deepEqual(args, {
            updateStatus: controlStatus.OK,
            jobStatus: jobStatus.ACTIVE,
          });

          return {};
        },
      };
    });
```

But it fails to validate the model, which is not mocked, so I think you need to mock model instantiation as well? :L

**Comment by ehtesham1996** [comment]
@jacktuck  can you share full example if possible

**Comment by jacktuck** [comment]
@ehtesham1996 Sorry I don't have an example to hand. I'd maybe do something similar to how dynamoose mocks itself here https://github.com/dynamoose/dynamoose/blob/master/test/unit/Model.js#L79

**Comment by fishcharlie** [comment]
@ehtesham1996 [This project](https://github.com/rrainn/aws-mockify) I created, along with [`dynamoose.aws.ddb.set`](https://dynamoosejs.com/guide/Dynamoose#dynamooseawsddbsetddb) and [`dynamoose.aws.ddb.revert`](https://dynamoosejs.com/guide/Dynamoose#dynamooseawsddbrevert) should do the trick.

**Comment by CesarJava** [comment]
So, any news on how can we mock DynamoDb so Dynamoose can actually use a mocked version?

What I'm doing now is mocking the model and it's functions, but this is slow and also not the best way to handle this, because I generate errors when I want, and not based on Dynamoose behavior.

**Comment by fishcharlie** [comment]
@CesarJava Lots of examples and information listed above. Please read the thread and research some of the options suggested.

**Comment by CesarJava** [comment]
@fishcharlie, the examples above mock dynamoose, like with sinon stubs. But this is not ideal, because errors generated by dynamoose itself can't be tested.
Your last comment above was exactly the first thing I tried. But instead I've used Jest mock dynamo with no success, then aws-SDK-mock with no success either when setting dynamoose to point to those, I always got the unhandled error that couldn't connect to local host

**Comment by fishcharlie** [comment]
@CesarJava Works for me:

```js
(async () => {
	const dynamoose = require("dynamoose");
	const MOCKAWS = require("aws-mockify");

	MOCKAWS.mock("DynamoDB", "getItem", (params, callback) => {
		if (params.Key.id.N === "2") {
			return callback("This is an AWS error in the mock.");
		}

		callback(null, {
			"Item": {
				"id": {
					"N": "1"
				},
				"name": {
					"S": "Tim"
				}
			}
		});
	});

	const ddb = new MOCKAWS.DynamoDB();
	dynamoose.aws.ddb.set(ddb);

	const User = dynamoose.model("User", {
		"id": {
			type: Number,
			hashKey: true
		},
		"name": String
	}, {
		"create": false,
		"waitForActive": false,
		"update": false
	});

	const user = await User.get({
		"id": 1
	});

	console.log(user);

	try {
		await User.get({
			"id": 2
		});
	} catch (e) {
		console.log("DynamoDB error: ", e);
	}
})();
```

And the console output:

```
charliefish@Charlies-MacBook-Pro tmp % node index.js
Document { id: 1, name: 'Tim' }
DynamoDB error:  This is an AWS error in the mock.
```

---

However, this is getting pretty off topic. None of this is really related to Dynamoose, but more related to your code, and the packages you are using. Dynamoose provides the tools to mock your database calls. You can use [`dynamoose.aws.ddb.local `](https://dynamoosejs.com/guide/Dynamoose#dynamooseawsddblocalendpoint), [`dynamoose.aws.ddb.set `](https://dynamoosejs.com/guide/Dynamoose#dynamooseawsddbsetddb) & [`dynamoose.aws.ddb.revert `](https://dynamoosejs.com/guide/Dynamoose#dynamooseawsddbrevert). Anything beyond that is kinda out of scope for Dynamoose.

If this continues to be off topic I will have to lock this thread.
