### ISSUE TITLE
Example of setting Array as Attribute Type

### ISSUE THREAD

**Issue by hassankhan** [automategreen/dynamoose#260]
Hi, thanks for this awesome library! 

Is there an example of using `Array` as an attribute type? Not having much luck trying to get it to work :/

**Comment by brandongoode** [comment]
@hassankhan - Hopefully you already found out that you can use arrays.  Just use `[type]`: https://dynamoosejs.com/api#attribute-types

**Comment by fishcharlie** [comment]
Due to lack of activity I'm closing this issue. If this didn't solve your problem please feel free to comment again.

**Comment by hassankhan** [comment]
@brandongoode's answer indeed helped, thanks!!
