### ISSUE TITLE
Allow setting DynamoDB client

### ISSUE THREAD

**Issue by hassankhan** [automategreen/dynamoose#261]
It would be cool if we could pass our own DynamoDB service client object. This is so we could use DAX, which requires a specially instantiated version of the regular client.

This could be something like a `client` property in the `Model` options.

**Comment by brandongoode** [comment]
I'm open to it.  #212

**Comment by fishcharlie** [comment]
Closing as a duplicate of #212

**Comment by fishcharlie** [comment]
I created a PR for this (#330). I need some help writing some tests, improving the documentation with an example, and testing it with DAX (since I have never used DAX before). If anyone would like to help please follow the instructions on that PR.
