### ISSUE TITLE
BatchPut and BatchDelete really use "options"?

### ISSUE THREAD

**Issue by Zweer** [automategreen/dynamoose#266]
AFAIK both batchPut and batchDelete have a "options" argument, but none of them seems to use it. Is there a reason for that?

I'm trying not to overwrite items in a batchPut (existing items use the default value of a field)

Thanks
Cya

**Comment by brandongoode** [comment]
The options are just for to keep the API consistent and allow for future options without breaking the current API. 

The DynomoDB BatchWriteItem operation doesn't support conditions.  We would need Amazon to add support for this feature first: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html

**Comment by Zweer** [comment]
Ok, thanks a lot!
