### ISSUE TITLE
the scan api can't not obtain the data,but using query with hash key can obtain the data 

### ISSUE THREAD

**Issue by liberty2015** [automategreen/dynamoose#268]
Hi,I met a problem that has troubled me for a long time:
in my dynamoDB,there is a table named device  with more than 8000 datas,when i use scan to find som data like this
`let filter = {
            FilterExpression: '<hashkey>=:<k>',
            ExpressionAttributeValues: {
                ":<k>": "<the value>"
            }
        };
        Device.scan(filter).exec().then(
            data => {
                console.log(data);
            },
            err => {
                console.error(err);
            }
        )`
some data can't find,but when i use query like this:
`Device.query({<hashkey>: {eq: '<the value>'}}).exec((err, datas) => {
            if (err) {
                console.error(err);
                return;
            }
            console.log(datas);
        });`
the data which can't be found by using scan appears again after using the query! And I use scan cmd through the aws cli ,the data also appear.This is weird.I really want to get help,which is very important to me.

**Comment by liberty2015** [comment]
I fix the problem with myself.The reason is :
> If the total number of scanned items exceeds the maximum data set size limit of 1 MB, the scan stops and results are returned to the user as a LastEvaluatedKey value to continue the scan in a subsequent operation.
from https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#scan-property
the code:
`
Device.scan({<hashKey>:"<the value>"}).parallel(2).exec().then(
            data => {
                console.log(data);
            }, err => {
                console.error(err);
            }
        )
`

**Comment by fishcharlie** [comment]
@liberty2015 Glad you got it working!!
