### ISSUE TITLE
Delete item from a string set?

### ISSUE THREAD

**Issue by alankarmisra** [automategreen/dynamoose#269]
Maybe I'm missing something obvious but how do I delete something from a string set in dynamoose without having to retrieve the object first?

For example I have a table Users with a document:
`{ id:'myid', myfield:['val1','val2]}`
and I want to remove val2 without having to retrieve the entire object first.

I tried something like:
`
Users.update({ id: 'myid',  '$DELETE': { myfield: [ 'val2' ] } }
`
but it seems to delete the entire field myfield instead of just deleting one value. What am I missing?!

And thank you for the amazing library! My life is better thanks to this! 

Reference: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.DELETE

**Comment by fishcharlie** [comment]
@alankarmisra Can you share your schema and model with us?

**Comment by fishcharlie** [comment]
Closing this issue due to no reply from the OP. Please comment if this is still an issue and we can look at it further.
