### ISSUE TITLE
How to query local dynamoDB using dynamoose?

### ISSUE THREAD

**Issue by sabreenakp** [automategreen/dynamoose#271]
As a developer, I don't want to connect all the time to Amazon web services, and I installed DynamoDB in my local computer referring the [AWS Docs.](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) I am using node.js in the backend.I am using dynamoose as the modeling tool for Amazon's DynamoDB in my production, How can I use the same dynamoose for querying my local DynamoDB tables for development?

**Comment by fishcharlie** [comment]
The code below should allow you to setup Dynamoose for use locally.

    var dynamoose = require('dynamoose');
    dynamoose.local('http://localhost:8000');

This assumes DynamoDB is running locally on port 8000. If you are not running DynamoDB Local on port 8000 you will have to update the second line above to reflect the correct port.

**Comment by sabreenakp** [comment]
Thanks
