### ISSUE TITLE
IAM role instead of access keys

### ISSUE THREAD

**Issue by tvb** [automategreen/dynamoose#273]
Why doesn't dynamoose accept IAM roles? Much more safe as you don't have to distribute access keys with the risk publishing them somewhere on the internet

info https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

**Comment by ricxsar** [comment]
Hello @tvb. I am a user of this library on an ec2 instance and it working fine on me without specifying access keys. I am assigning `AmazonDynamoDBFullAccess` policy on the role assigned to ec2 instance.

**Comment by fishcharlie** [comment]
@tvb, @ricxsar is correct. I have used this library using IAM roles assigned to EC2 instances and it works just fine. Dynamoose is just a wrapper for the AWS Javascript SDK, so the core of this library is still AWS.

I'm going to close this issue now, if you have any more questions regarding this or need help please feel free to reply again.
