### ISSUE TITLE
Error: indexes are not synchronized and update flag is set to false

### ISSUE THREAD

**Issue by jignesh248** [automategreen/dynamoose#278]
I have a user model with a GSI, I am adding a new GSI on phoneNumber which was not there before,
I am getting this error now on starting my node app.
I am using local version of dynamodb as of now, update option is set to true, so probably there is bug. I can't delete DB each time I change schema. I tried to debug, but I think I am not good with debugging async code( Any suggestions ).

```
const validator = require('validator');
let dynamoose = require("dynamoose");
require('../db')(dynamoose);
const uuidv4 = require('uuid/v4');

let UserSchema = new dynamoose.Schema({
        ID: {
            type: String,
            default: uuidv4,
            hashKey: true
        },
        email: {
            type: String,
            trim: true,
            validate: (x) => validator.isEmail(x),
            required: true,
            lowercase: true,
            index: {
                global: true,
                name: 'UserByEmailIndex',
                project: true, // ProjectionType: ALL
                throughput: 5 // read and write are both 5
            }
        },
        phoneNumber: {
            type: String,
            trim: true,
            validate: (x) => validator.isMobilePhone(x,'any'),
            required: true,
            index: {
                global: true,
                name: 'UserByPhoneIndex',
                project: true, // ProjectionType: ALL
                throughput: 5 // read and write are both 5
            }
        },

        password: String,
        salt: String
    },
    {
        create: true,                                 // Create table in DB, if it does not exist,
        update: true,                                   // Update remote indexes if they do not match local index structure
        waitForActive: true,                            // Wait for table to be created before trying to use it
        waitForActiveTimeout: 180000,                   // wait 3 minutes for table to activate
        saveUnknown: true,
        useDocumentTypes: true,
        useNativeBooleans: true,
        timestamps: true
    });

module.exports.User = dynamoose.model('Users', UserSchema);
```

**Comment by jignesh248** [comment]
Okay may be I found it, I didn't had phoneNumber already in table as it was not a required value, as such creation of global Index might have been failing, but we can improve on the error message.

**Comment by jignesh248** [comment]
Any update on this, anybody else facing the same issue?

**Comment by deependrax** [comment]
providing update: true in dynamoose.model as option will solve this.
module.exports.User = dynamoose.model('Users', UserSchema, {update: true});

**Comment by deependrax** [comment]
but this is creating another issue for me, it is taking a table lock on server up causing a downtime which i want to avoid on prod.

**Comment by jignesh248** [comment]
ohh, I was passing it on object used as second argument for new Schema all the while, and not as their argument to dynamoose.model.

Thanks for clarification

**Comment by shierro** [comment]
Hey guys, does `waitForActive: true` have a callback/trigger? what can we do to determine if table is already active

**Comment by fishcharlie** [comment]
@shierro Currently the `waitForActive` function doesn't have a callback. You would have to build that manually using the AWS SDK.
