### ISSUE TITLE
Map and List attributes

### ISSUE THREAD

**Issue by Vurk** [automategreen/dynamoose#28]
Hi, is there any way to set the attribute value to DynamoDB Map and/or List? When I insert a new item with an array of objects, it is set to String in DynamoDB but the same item, inserted directly to DynamoDB set the attribute to Map. The same way with List.

Thanks

**Comment by brandongoode** [comment]
Yes.

Here's the test case you can use as an example: 

https://github.com/automategreen/dynamoose/blob/b9830d3b5c2334dba31ceb7b3081bea44162c541/test/Schema.js#L108-L123

**Comment by Vurk** [comment]
Hi, I have setup my schema as the example but it is still saving the map type as string in dynamodb. This is my schema:

Schema = new Schema({
      id: { type: String, require: true, hashKey: true },
      createAt: { type: String, require: true },
      code: String,
      date: { type: Date, require: true },      
      user: { 
        type: 'map',
        map: {
          name: { type: String, require: true },
          famname: { type: String, require: true },
          idcode: { type: String, require: true }          
        },
        require: true
      },
      client: { 
        type: 'map',
        map: {
          clientId: { type: String, require: true },
          contact: { type: String, require: true },
          phone: Number,
          email: { type: String, require: true }
        },
        require: true
      },
      services: { 
        type: 'list',
        list: [
          {
            serviceId: { type: String, require: true },
            title: { type: String, require: true },
            description: { type: String, require: true }
          }
        ],
        require: true
      },
      comments: String
    },
    {
      throughput: {read: 5, write: 5}
    });

The user, client and services are all json objects. I´m doing some mistake?

Thanks.

**Comment by brandongoode** [comment]
@Vurk - Sorry I left out a step.  You need to set the opotion `useDocumentTypes` to `true`.

https://github.com/automategreen/dynamoose/blob/b9830d3b5c2334dba31ceb7b3081bea44162c541/test/Schema.js#L215

I really you do a better job with the Readme -- PR for missing documentation is always welcome.

**Comment by Vurk** [comment]
All works perfectly. Thanks!
