### ISSUE TITLE
Query Index Name or Partition Key?

### ISSUE THREAD

**Issue by fishcharlie** [automategreen/dynamoose#288]
This might be a really dumb question. But it's a question I have. Once I have the answer I would be more than happy to create a PR to improve the documentation and add some extra detail regarding this.

Take the following example model and schema.

```
var itemSchema = new dynamoose.Schema({
	_id: String,
	userid: String,
	description: String,
	active: Boolean
}, {
	timestamps: true
});

var model = dynamoose.model(process.env.DATABASE_PREFIX + '_Item', itemSchema);
```

I added the following index to DynamoDB.

<img width="762" alt="screen shot 2018-02-18 at 11 13 47 pm" src="https://user-images.githubusercontent.com/860375/36364533-d2dfb4ca-1501-11e8-9bdd-c1747b0d4299.png">

To query this, would I do the following?

```
Item.query("userid-index-1").eq("abcd")
.and()
.filter("active").eq(true)
.all()
.exec(
```

OR the following?

```
Item.query("userid").eq("abcd")
.and()
.filter("active").eq(true)
.all()
.exec(
```

**Comment by ajwild** [comment]
I think you need to change your schema from:
```
userid: String,
```
to:
```
userid: {
  type: String,
  index: {
    global: true,
    name: 'userid-index-1',
    project: true,
  },
},
```
After that your second query should work. Depending on your data it may also be worthwhile setting "active" as the range key and using `where()` instead of `filter()`. I also think `and()` isn't required.
