### ISSUE TITLE
Timestamp fields suport like createdAt and updatedAt

### ISSUE THREAD

**Issue by darthapple** [automategreen/dynamoose#29]
What about have support to createdAt fields and updatedAt fields like others? CreatedAt  automatically saves datetime when record was created and updatedAt a datetime when record was last saved.
This maybe achieved using a New option when a define a schema.

**Comment by brandongoode** [comment]
Good idea.

We could model it after mongooses timestamp option: http://mongoosejs.com/docs/guide.html#timestamps

If you want to add a createdAt field today it can be done like this:

```js
var userSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
    default: shortId.generate
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});
```

The new option would be something like this:

```js
var userSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
    default: shortId.generate
  },
  timestamps: true
});
```

**Comment by darthapple** [comment]
@brandongoode I'll implement in the way you have suggested, whenever, with these two syntax:
1) In this case we can set the name of _timestamp_ fields (_\<fieldname\>_):
```javascript
var userSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
    default: shortId.generate
  },
  timestamps: {
        createdAt: '<fieldname>',
        updatedAt: '<fieldname>'
});
```

2) In this case the field will use default names: _createdAt_ and _updatedAt_
```javascript
var userSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
    default: shortId.generate
  },
  timestamps: true
});
```

**Comment by brandongoode** [comment]
@darthapple  - by "I'll implement it" are you saying you are going to create a PR?  That would be great, but not required.

**Comment by darthapple** [comment]
Yes, this is the idea? What do you think about?

**Comment by brandongoode** [comment]
Yes that's great.  The only change is it needs to be in the options section of the Schema.  I had it in the wrong section too. 


```js
var userSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
    default: shortId.generate
  }
}, {
  timestamps: {
    createdAt: '<fieldname>',
    updatedAt: '<fieldname>'
  }
});
```

```js
var userSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
    default: shortId.generate
  }
}, {
    timestamps: true
});
```

**Comment by darthapple** [comment]
OK. n problem. Today at night I'll create a PR with code.
