### ISSUE TITLE
Dynamoose is taking table lock on startup for syncing index can this be avoided

### ISSUE THREAD

**Issue by deependrax** [automategreen/dynamoose#302]
using update: true on dynamoose.model 
Eg. dynamoose.model("Test", schemas.testSchema, {update: true});

is taking a table lock on server up causing a downtime which i want to avoid on prod.

if i do update: false i get an error.
Error: indexes are not synchronized and update flag is set to false

**Comment by ratneshsinghparihar** [comment]
can you try  drop the table and re-create it (not with code)  https://forums.aws.amazon.com/thread.jspa?threadID=224522

**Comment by fishcharlie** [comment]
@deependrax Can we see your schema?

**Comment by deependrax** [comment]
I think i resolved it by setting both create & update set to true in dymoose default
dynamoose.setDefaults({
    create: false,
    update: false
});

now i think i just need to make sure i handle migration gracefully.

**Comment by fishcharlie** [comment]
@deependrax Glad you got it working!!

**Comment by maulerjan** [comment]
Does this still happen?

Apart from using Dynamoose in my actual app I'm also using Dynamoose in my deployment pipelines to synchronize the defined model with the database.

Does it mean every time my pipeline runs it issues a lock on each table I've updated indexes for?

**Comment by fishcharlie** [comment]
@maulerjan Please read this documentation [here](https://dynamoosejs.com/api#dynamoosemodelname-schema-options). The options you are probably interested in are `create`, `update`, and `waitForActive`.

As far as I know, DynamoDB won't lock the table when creating indexes.

> Part of this operation involves backfilling data from the table into the new index. During backfilling, the table remains available.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SQLtoNoSQL.Indexes.html

**Comment by dolsem** [comment]
I think this can be related to #453. I haven't checked out new versions of the library in a long time, I'll do it some time soon and check if the problem is still there.
