### ISSUE TITLE
Query should always return an array?

### ISSUE THREAD

**Issue by craigsketchley** [automategreen/dynamoose#32]
Hi,

I may be doing something wrong but it's my understanding that calling query on a model should return an array of the items. If that's the case then shouldn't it return an empty array when no items are found for that query? I think currently it's `undefined`.

At the moment I have to check if the returned value is defined every time I call query (unless I'm doing it wrong):

```
Dog.query({breed: {eq: 'Beagle'} }, function (err, dogs) {
  if (!!dogs) {
    dogs.map(function(dog) {
      // Do something with a dog
    });
  }
});
```

It'd be nicer and less error prone to just assume dogs is a possibly empty array of the items I've queried.

**Comment by craigsketchley** [comment]
Great library btw. This is the reason I finally started using DynamoDB.

**Comment by brandongoode** [comment]
Thanks

It should always return an array.  The array will be empty if no results are found.  I just double checked.  

The only time it would be undefined is if an error happened.  Can you add a test to see if err exists.
