### ISSUE TITLE
Transactions support

### ISSUE THREAD

**Issue by tony-gutierrez** [automategreen/dynamoose#33]
It would be nice to support transactions as outlined in the official AWS SDK for Java.

There is a push to get them added to the JS SDK here: aws/aws-sdk-js#1004

**Comment by brandongoode** [comment]
I'll keep an I on the AWS change.

**Comment by fishcharlie** [comment]
@tony-gutierrez Looks like this issue was closed and will not be making it into the AWS JS SDK for the time being. If that issue gets reopened and implemented we can revisit this. But for the time being I'm going to close this issue now since Amazon isn't going to implement it anytime soon.

**Comment by annabunches** [comment]
Amazon just announced support for server-side transactions in dynamodb, and their example code is specifically in the javascript sdk. Time to revisit this?

https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/

**Comment by annabunches** [comment]
Oh never mind y'all are already on top of this :)

**Comment by fishcharlie** [comment]
@annabunches This has been released as of [Dynamoose version 1.2.0](https://github.com/dynamoosejs/dynamoose/releases/tag/v1.2.0).

#472
