### ISSUE TITLE
Custom table names

### ISSUE THREAD

**Issue by tony-gutierrez** [automategreen/dynamoose#34]
Is there a way to override table names?

**Comment by brandongoode** [comment]
Sorry.  No.  DynamoDB does not support changing the table name. You would have to create a new table and copy the data over.

**Comment by tony-gutierrez** [comment]
I wasnt thinking an alteration to the name, I was more thinking a custom name before create. Vogels supports this.

**Comment by brandongoode** [comment]
You can add a prefix to the name using a prefix option.

Can you point me to a Vogels example?

**Comment by tony-gutierrez** [comment]
In Vogels, the name of the class and the table name are more divorced. Here's an example schema:

```
var Group = vogels.define('Group', {
  hashKey : 'id',
  timestamps : false,

  schema : {
    id: vogels.types.uuid(),
    userId: Joi.string().required(),
    name: Joi.string().required()
  },
  indexes : [{
    hashKey : 'userId', name : 'UserIndex', type : 'global'
  }],
  tableName: function () {
    return 'XXproject_' + process.env.NODE_ENV + '_groups';
  }
});
```

**Comment by tony-gutierrez** [comment]
In reality the prefix option will probably be sufficient for what I'm trying to do. I cant seem to find it documented.

**Comment by brandongoode** [comment]
I need to add that to the documentation.

You can set the prefix in two ways.  Either per schema or globally.  I normally use the global method.


Globally:

```js
var dynamoose = require('dynamoose');
dynamoose.setDefaults( { prefix: 'XXproject_' + process.env.NODE_ENV + '_' });
```

Per table:
```js
var groupSchema  = new Schema({
  ...
},
{
  prefix: 'XXproject_' + process.env.NODE_ENV + '_'
});
```

**Comment by aaronshaf** [comment]
It'd be nice to manually specify the table name
