### ISSUE TITLE
can you search any key with .get?

### ISSUE THREAD

**Issue by elgubenis** [automategreen/dynamoose#35]
hi, i'd like to know if the key someone is querying for using .get needs to be indexed, or if any key can be searched withing .get? I'm new to dynamodb and had trouble creating a schema where i used .get({ email: 'username@domain.tld' }), it did not return anything even though the records were there.

I use dynamoose with the serverless framework, dynamoose already works for me for creating items in dynamo, but the missing piece is finding them (efficiently), I have some example of my user scheme, maybe someone could give me any comment on if thats correct, or not?

```js
const userSchema = new Schema({
  id: { // here i generate node-uuid v1's
    type: String,
    hashKey: true,
  },
  email: {
    type: String,
    trim: true,
    required: true,
    index: { // here i also tried stuff with rangeKeys but i failed
      global: true, 
      project: true,
    },
  },
  givenName: String,
  familyName: String,
});
```

also, if anybody has a "simple and clean" dynamodb with node/js tutorial or documentation website/repository i'd be really thankful.

**Comment by elgubenis** [comment]
this is my register function:

```
const User = dynamoose.model('User', userSchema);

exports.register = (req, res, next) => {
  const body = req.body;
  User.get({ email: body.email }).then(result => {
    if (result) return next(new Error('User already exists'));
    else {
      const newUser = new User({ id: id(), email: body.email });
      return newUser.save().then(result => {
        if (result) return res.json({ success: true });
        next(new Error('User was not created'));
      });
    }
  }).catch(err => next(err));
};
```

I never get to the 'User already exists' part, it always creates a new item, even though the email im looking for already exists.

**Comment by brandongoode** [comment]
Only the hash key and range key of the main index can be used with `.get(...)`.  For all other indexes you need to use query or queryOne.

```js
const User = dynamoose.model('User', userSchema);

exports.register = (req, res, next) => {
  const body = req.body;
  User.queryOne({ email: body.email }).then(result => {
    if (result) return next(new Error('User already exists'));
    else {
      const newUser = new User({ id: id(), email: body.email });
      return newUser.save().then(result => {
        if (result) return res.json({ success: true });
        next(new Error('User was not created'));
      });
    }
  }).catch(err => next(err));
};
```

**Comment by elgubenis** [comment]
oh nice, would not using a rangeKey for searching by email slow down the fetch?

**Comment by brandongoode** [comment]
rangeKey is more for when you have identical hash keys.  Say comments on a blog post where the hash key is the blog post id and the range key is the comment id.  You use just the hash key to get all the comments and the range key when you need a single comment.

The global index is correct for your use case.  Query is very efficient and fast.  Scan is not as efficient.

**Comment by elgubenis** [comment]
thank you very much for your help and advice @brandongoode! I used mongoose a lot, so switching to dynamo with dynamoose  was 'almost' like a breeze, there are still some differences and caveats of dynamo I need to learn, but so far it looks promising.

**Comment by elgubenis** [comment]
I got an error, using this scheme:

```js
{
  id: {
    type: String,
    hashKey: true,
  },
  email: {
    type: String,
    trim: true,
    required: true,
  },
  givenName: String,
  familyName: String,
}
```


```json
"errorMessage": "Query condition missed key schema element: id"
"errorType": "ValidationException"
"stackTrace": [10]
0:  "Request.extractError (/var/task/api/node_modules/aws-sdk/lib/protocol/json.js:43:27)"
1:  "Request.callListeners (/var/task/api/node_modules/aws-sdk/lib/sequential_executor.js:105:20)"
2:  "Request.emit (/var/task/api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)"
3:  "Request.emit (/var/task/api/node_modules/aws-sdk/lib/request.js:595:14)"
4:  "Request.transition (/var/task/api/node_modules/aws-sdk/lib/request.js:21:10)"
5:  "AcceptorStateMachine.runTo (/var/task/api/node_modules/aws-sdk/lib/state_machine.js:14:12)"
6:  "/var/task/api/node_modules/aws-sdk/lib/state_machine.js:26:10"
7:  "Request.<anonymous> (/var/task/api/node_modules/aws-sdk/lib/request.js:37:9)"
8:  "Request.<anonymous> (/var/task/api/node_modules/aws-sdk/lib/request.js:597:12)"
9:  "Request.callListeners (/var/task/api/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
```

I still did something wrong huh?

**Comment by elgubenis** [comment]
got it:
```js
{
  id: {
    type: String,
    hashKey: true,
  },
  email: {
    type: String,
    trim: true,
    required: true,
    index: {
      global: true,
      project: true,
    },
  },
  givenName: String,
  familyName: String,
})
```

**Comment by brandongoode** [comment]
You type much faster than I.  Glad you got it working.

**Comment by elgubenis** [comment]
can you recommend a way to make a relationship? in my case a user can have many templates, (one-to-many)

```js
const userSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
  },
  email: {
    type: String,
    trim: true,
    required: true,
    index: {
      global: true,
      project: true,
    },
  },
  givenName: String,
  familyName: String,
});
dynamoose.model('User', userSchema);

const templateSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
  },
  name: {
    type: String,
    required: true,
    trim: true,
  },
  user: ... how? ...,
});
dynamoose.model('Template', templateSchema);
```
my thought was that the user needs to be a rangeKey?

**Comment by elgubenis** [comment]
maybe, like this? 
```js
{
  id: {
    type: String,
    rangeKey: true,
  },
  name: {
    type: String,
    required: true,
    trim: true,
  },
  user: {
    type: String,
    hashKey: true,
  },
}
```

**Comment by brandongoode** [comment]
That's pretty much how I do it.  I normally name the the hashKey something like `userId` so I know what it references.

```js
{
  userId: {
    type: String,
    hashKey: true,
  },
  id: {
    type: String,
    rangeKey: true,
  },
  name: {
    type: String,
    required: true,
    trim: true,
  }
}
```

**Comment by jignesh248** [comment]
queryOne is not included in Documentation, I will try to create a PR sometime as there are too many missing functionalities in documentation and may also try to contribute to code.

**Comment by fishcharlie** [comment]
@jignesh248 #298
