### ISSUE TITLE
Implementing data dependent behavior to a Schema or a model?

### ISSUE THREAD

**Issue by reselbob** [automategreen/dynamoose#38]
Help? If you can? 

Is there any way I can do this:

var User  = new Schema({
ssn:{
    type: string,
    hashKey: true
},  
firstName: {
    type: string,
   required:true
  },
  lastName: {
    type: string,
    required:true
  },
 userName: {
    type: string,
    default: function() { return this.lastName + this.firstName }
  }
});

It seems that *this* executes in the scope of the attribute. I am hoping to get to the values of the model before saving. Any help that can be provided, thanks triple most in advance!

**Comment by brandongoode** [comment]
The default function cannot reference the current model values. 

If you do not need the userName attribute stored in DyanmoDB you could use a virtual.  

```js
var userSchema = new Schema({
  ssn:{
    type: string,
    hashKey: true
  },

  firstName: {
    type: string,
    required:true
  },
  lastName: {
    type: string,
    required:true
  }
});

var userName = userSchema.virtual('userName')

userName.get(function () {
  return this.firstName + ' ' + this.lastName;
 });

 userName.set(function (v) {
  var parts = v.split(' ');
  this.firstName = parts[0];
  this.lastName = parts[1];
 });
```

If you do need userName stored in the DB then I would use a static model function (this is what I do).

```js
var userSchema = new Schema({
  ssn:{
    type: string,
    hashKey: true
  },

  firstName: {
    type: string,
    required:true
  },
  lastName: {
    type: string,
    required:true
  }
});

var User = dynamoose.model('User', userSchema);

User.new = function (user) {
  user.userName = user.firstName + ' ' + user.lastName;
  return User.create(user);
};

// Then use the "new" method to create a user
User.new({ssn: "123456789", firstName: "Brandon", lastName: "Goode"})
.then(function(bgUser) {
  console.log(bgUser.userName); // should be "Brandon Goode"
});
```

**Comment by reselbob** [comment]
Thank you. Let me take your tripe excellent thinking for a spin.

**Comment by reselbob** [comment]
Just to make sure I am understand things correctly:

var User = dynamoose.model('User', userSchema);

User.new = function (user) {
  user.userName = user.firstName + ' ' + user.lastName;
  return User.create(user);
};

// Then use the "new" method to create a user
User.new({ssn: "123456789", firstName: "Brandon", lastName: "Goode"})
.then(function(bgUser) {
  console.log(bgUser.userName); // should be "Brandon Goode"
});

User.new is a model method, thus needs to be written outside of the file in which I define the Schema. ( I defined each Schema in its own file.) Tell me please, is my understanding accurate?

**Comment by brandongoode** [comment]
You're correct.  I defined each schema in its own file and export the model.

```js
// Complete User.js file

var userSchema = new Schema({
  ssn:{
    type: string,
    hashKey: true
  },

  firstName: {
    type: string,
    required:true
  },
  lastName: {
    type: string,
    required:true
  },
  userName: {
    type: string,
    required:true
  }
});

var User = dynamoose.model('User', userSchema);

User.new = function (user) {
  user.userName = user.firstName + ' ' + user.lastName;
  return User.create(user);
};

module.exports = User;
```

**Comment by reselbob** [comment]
Thank you for the help. I really, really appreciate it.

**Comment by kevinswarner** [comment]
Are virtual fields still supported in the current version? I cannot find anything in the documentation. Maybe the serializers is the way to achieve this now? Thanks.
