### ISSUE TITLE
How to achieve geospatial

### ISSUE THREAD

**Issue by mbalex99** [automategreen/dynamoose#41]
In mongoose you can do this for a schema attribute:

``` javascript
geo: {
        type: [Number],
        index: '2d'
}
```

How do you achieve geo queries with dynamoose.

Awesome library by the way.

**Comment by brandongoode** [comment]
First, sorry for not replying earlier.  I somehow overlooked this issue. 

I don't know much about mongoDB geo queries, but you may be able to accomplish the same thing with DynamoDB maps.
