### ISSUE TITLE
Use version ^2.1.0 instead of 2.1.* of AWS-sdk

### ISSUE THREAD

**Issue by davidhouweling** [automategreen/dynamoose#42]
Is there a particular reason you've locked it down to 2.1.* rather than just using ^2.1.0.

I would imagine a company such as Amazon would understand semver and therefore would not break this within the 2.* range. This impacts on other libraries that may use ^2.3.0 for example, in that they are using two individual AWS-sdk instances, rather than the same instance.

**Comment by brandongoode** [comment]
There was no real reason.  Feel free to send me a PR with the change.
