### ISSUE TITLE
Inconstant in Updating Items

### ISSUE THREAD

**Issue by fishcharlie** [automategreen/dynamoose#46]
I'm trying to run the code below to update the value of `mynumber` for the User where userid matches the main element. Problem is about half the time it works perfectly and updates just fine. The other half of the time it doesn't update the user record at all and the `mynumber` value just stays the same. If it was failing all the time I would think it was a problem on my part but it works perfectly sometimes and other times completely fails. Is this a Dynamoose issue or is there something I'm doing wrong?

    function updateData(userid, value) {
        User.get(userid, function(err, user) {
            user.mynumber = user.mynumber + value;
            user.save(function(err) {});
        });
    };

**Comment by brandongoode** [comment]
There could be several reason it's failing. Most likely DynamoDB rejected the save.

Can you log the err and provide the output.  

```js
function updateData(userid, value) {
    User.get(userid, function(err, user) {
        user.mynumber = user.mynumber + value;
        user.save(function(err) {
            if(err) console.log(err); // <----  capture errors
        });
    });
};
```

**Comment by fishcharlie** [comment]
`err` is always returning null. Even when it doesn't work.

**Comment by brandongoode** [comment]
Can you provide your schema for User and add a log of the user object before the save?

**Comment by fishcharlie** [comment]
Logging the user before hand works perfectly has the correct value. I did realize that in my app it's checking the value before it actually finishes saving (and runs the callback). BUT that doesn't explain why in the AWS console it doesn't even update.

I have attached my user schema below. I have removed a lot of the unnecessary fields. Been working to isolate the issue as much as I can.

    var dynamoose = require('dynamoose');

    var userSchema = new dynamoose.Schema({
        _id: String,
        mynumber: Number
    });

    module.exports = dynamoose.model('User', userSchema);

**Comment by brandongoode** [comment]
Any chance your preforming a save after with the old value.

You can try running it with DEBUG on.  That will show what is sent to AWS.

```sh
DEBUG=dynamoose* node app.js
```

**Comment by fishcharlie** [comment]
I'm defiantly not changing `mynumber` and saving after the save I'm talking about. BUT I might be running a save and changing other values after the fact. Would that cause an issue? If so I can just build some call backs to wait until the first save is done.

Below is the output of the most interesting part of the debug. I found. Both of the following sections were printed one after another. Looks like it updates the item and sets `mynumber` then the next thing gets the item and hasn't updated it.


    dynamoose:model updateItem +0ms { TableName: 'User',
    Key: { _id: { S: 'a6ad00ac291a19d953efb91820d1234e2263b28a' } },
    ExpressionAttributeNames: { '#_n0': 'mynumber' },
    ExpressionAttributeValues: { ':_p0': { N: '1' } },
    ReturnValues: 'ALL_NEW',
    UpdateExpression: 'SET #_n0 = :_p0' }

    dynamoose:model getItem response +291ms { Item: 
    { mynumber: { N: '0' },
    _id: { S: 'a6ad00ac291a19d953efb91820d1234e2263b28a' } } }

**Comment by brandongoode** [comment]
It could be the save on the other values.  When you call `.save()` all attributes in the current object are written.  If you call `User.update(key, {mynumber: xyz})` only the updated value will be written to DynamoDB.

**Comment by fishcharlie** [comment]
I could have sworn I tried update and that didn't work (but I could be wrong). But I was able to fix it by adding callback functions. Tried it about 6 times or so and it seems to be working. Of course could still be failing but 6/6 seems pretty good. If I run into another issue I will be sure to create another. Thank you SO much @brandongoode for your help!!

**Comment by brandongoode** [comment]
Great!  I'm happy its working.
