### ISSUE TITLE
npm version != git release?

### ISSUE THREAD

**Issue by elgubenis** [automategreen/dynamoose#47]
hey,

i stumpled upon a version 5 on npm, but when i install it i can find nothing from the 0.5 release, example the word "timestamp" inside lib/Schema.js, did you maybe not publish the same source as you released in git?

**Comment by elgubenis** [comment]
your advice using the git repo directly:

```json
  "dependencies": {
    "dynamoose": "git://github.com/automategreen/dynamoose.git",
    ...
  }
```

works obviously, but it would be cool to have the npm 0.5 version working aswel, could you republish?

**Comment by brandongoode** [comment]
That's not cool -- Let me check to see what I did wrong.

**Comment by brandongoode** [comment]
I failed to pull the PR updates to the computer from which I did the npm publish.   This left out several PRs, timestamps being one, from the 0.5 release.  The 0.6 should now have them.

**Comment by elgubenis** [comment]
thank you very much.

**Comment by brandongoode** [comment]
@elgubenis -- thanks for letting me know about the issue.
