### ISSUE TITLE
model.toJSON()?

### ISSUE THREAD

**Issue by elgubenis** [automategreen/dynamoose#48]
hi,

im looking for a way to re-use the json of 1 model to create another one, how could that be accomplished right now without using any 3rd party library?

**Comment by brandongoode** [comment]
I'm not sure I follow.  Do you want to create a new record with the same schema?

If you do, you would set the key values and save the model.  If the key values change it will create a new record.

**Comment by elgubenis** [comment]
i would like to create a new model, with a different schema, (having some keys in common) using the data/json of the old model,

like Template.get().then(remplate => new File(template).save())

**Comment by elgubenis** [comment]
i did this,
```js
JSON.parse(JSON.stringify(template))
```
and it works

**Comment by brandongoode** [comment]
Great solution -- thanks for sharing.
