### ISSUE TITLE
Boolean type maps to String?

### ISSUE THREAD

**Issue by craigsketchley** [automategreen/dynamoose#55]
Hey,

Just wondering what I'm missing, how come you're mapping Boolean types to String in DynamoDB? I thought DynamoDB supported a Boolean type?

**Comment by brandongoode** [comment]
Dynamoose predates support for Boolean types in DynamoDB.   I've been thinking about adding a option to toggle the behavior.  I do not want to change the current default behavior as it would break the existing deployments.
