### ISSUE TITLE
Does dynamoose support the notion of beforeSave and afterSave events?

### ISSUE THREAD

**Issue by reselbob** [automategreen/dynamoose#56]
I want to be able to support an attribute that describes the over all state of a Model instance just before it is saved, as shown below. Tell me please, does dynamoose support beforeSave and afterSave events/methods.... if not, might you point me in a direction where I can make this happen. Thanks in advance!

```javascript
var schema = new Schema({
  ssn: {
    type: String,
    hashKey: true,
  },
  firstName: {
    type: String,
   required: true
  },
  lastName: {
    type: String,
   required: true
  },
  dob: {
    type: Date,
    required: true
  },
 gender{
    type: String,
   required: true
},
birthdayGift{
   type:String
}
});


var Person = dynamoose.model('Person', schema);

Person.beforeSave() = function(){
//pseudo code
 if(today == this.dob && this.gender == "male"){
     this.birthday == "box";
  }
  if(today == this.dob && this.gender == "female"){
    this.birthday == "ball";
  }

}

```

**Comment by brandongoode** [comment]
Nothing exist for the use case you have.  You can have set/get function per attribute in the schema definition, but the function does not have the model as this.

set: function
Adds a setter function that will be used to transform the value before writing to the DB.

get: function
Adds a getter function that will be used to transform the value return from the DB.

**Comment by reselbob** [comment]
So, is I were to do the `set()` as below, would `set()` be called whenever the model was saved? 

```javascript
.
.
birthdayGift{
   type:String
}

birthdayGift.set(function(){
  if(today == this.dob && this.gender == "male"){
     this.birthdayGift == "box";
  }
  if(today == this.dob && this.gender == "female"){
    this.birthdayGift == "ball";
  }
})
```

**Comment by brandongoode** [comment]
It would be called, but you can't reference the model from within the function.  `this.dob` and `this.gender` would be undefined.

**Comment by EugeneHerasymchuk** [comment]
it's actually a nice idea and can be implemented as an external npm package. 
So many cases where validation has to be before storing to DB and every time you have to do it manually.

**Comment by jignesh248** [comment]
I also want to have it, so that I can directly save create, update and delete to elastic search from models itself, that way I can abstract away it from api endpoints. Would be much cleaner, though it is not needed.
