### ISSUE TITLE
Model Unique

### ISSUE THREAD

**Issue by fishcharlie** [automategreen/dynamoose#57]
So in MongoDB and Mongoose it automatically has a section for id. Doesn't seem like Dynamoose/DynamoDB has an option for that. So far I've been creating a random string every time I save a new record that is the ID.

One of the problems with that is if the ID ever overlaps with another ID then that is a problem. Is there a way to set that to be `unique: true`? According to the documentation there is an option for required but I can't find anything about unique. I know it is an option in Mongoose tho.

Finally is there a better way to handle generating a unique ID for every record? If I just set unique to true then I will have to retry that save since it will have failed which adds a layer of complexity. So is there a better way to handle this?

**Comment by brandongoode** [comment]
Here's what i do for my IDs:

```js
var shortId = require('shortid');
var dynamoose = require('dynamoose');
var Schema = dynamoose.Schema;


var userSchema = new Schema({
  id: {
    type: String,
    hashKey: true,
    default: shortId.generate
  },
  ...
});

**Comment by fishcharlie** [comment]
So what would happen if by some random chance it generated the same id for multiple records?

**Comment by brandongoode** [comment]
That depends on what command you use.  If you use `.save` or `.put` it will overwrite the existing record.  If you use `.create` it will error because the table key will be duplicated. 

You can also call `.save` with the option `{overwrite: false}`.  This is what `.create` does by default.

**Comment by sevenOneHero** [comment]
I dont understand why is this closed .  This is still an issue, there is no way to gurantee a unique primary key generation . Is there ?

**Comment by fishcharlie** [comment]
@sevenOneHero How does @brandongoode's comment above not answer the original question and therefor close the issue?

**Comment by JEmpDev** [comment]
> Here's what i do for my IDs:
> 
> ```js
> var shortId = require('shortid');
> var dynamoose = require('dynamoose');
> var Schema = dynamoose.Schema;
> 
> 
> var userSchema = new Schema({
>   id: {
>     type: String,
>     hashKey: true,
>     default: shortId.generate
>   },
>   ...
> });
> ```

if I use this method (with `default` option), do is still have to set the id manually? Because if I don't I'm getting a `ModelError: Hash key required: id`

**Comment by manast-apsis** [comment]
@sevenOneHero if you use a cryptographically secure uuid generation then it is guaranteed, or well, at least the chances that it happens are so small that it will never happen in practice.

**Comment by fabidick22** [comment]
![image](https://user-images.githubusercontent.com/8176821/87212735-b8167400-c2e5-11ea-831e-d5fec22c3a5c.png)
I think this feature would be great, [uuid](https://www.npmjs.com/package/uuid) is a dependency of this package, could this help the implementation of this feature?

**Comment by fishcharlie** [comment]
@fabidick22 Not sure why Dynamoose should be responsible for this. Why can't you just use the `default` setting and use UUID yourself? Like the example @brandongoode gave above. What would be the true advantage of having this built in? It saves what? 1 (maybe 2) lines?

**Comment by fabidick22** [comment]
Yes, I am using UUID to solve this. But why not? It would be great if the library assigns a default UUID if a value is not specified, this way we avoid adding a new dependency to our application. But this is only a suggestion, you should not be considered a priority.

in case someone needs it
```javascript
const dynamoose = require("dynamoose");
const { v4: uuidv4 } = require('uuid');

const schema = new dynamoose.Schema({
    "id": {
        "type": String,
        "hashKey": true,
        "default": uuidv4()
    }
})
```

**Comment by fishcharlie** [comment]
@fabidick22 As a Dynamoose user, what would you like the syntax to be for defining a schema with this UUID property? Do you think there should be a setting on the property? Do you think it should be a different type? Do you think there should be a custom default value (ex. `"default": dynamoose.uuid`)? Do you think it should be automatic given certain conditions?

Just curious how you'd like to see this work if implemented.

**Comment by bros4president** [comment]
> Yes, I am using UUID to solve this. But why not? It would be great if the library assigns a default UUID if a value is not specified, this way we avoid adding a new dependency to our application. But this is only a suggestion, you should not be considered a priority.
> 
> in case someone needs it
> 
> ```js
> const dynamoose = require("dynamoose");
> const { v4: uuidv4 } = require('uuid');
> 
> const schema = new dynamoose.Schema({
>     "id": {
>         "type": String,
>         "hashKey": true,
>         "default": uuidv4()
>     }
> })
> ```

Please don't call `uuidv4` when declaring the default value. It will be executed once at schema definition and then everytime you call `Model.create`, resulting in unwanted duplicated partition keys. If it's a single key, a `ConditionalCheckFailedError` will be raised, but in the case of a composite key the mistake may end up unnoticed.

Use `default: uuidv4` or `default: () => uuidv4()` instead to get a different value on every call :)
