### ISSUE TITLE
Need some help with indexing

### ISSUE THREAD

**Issue by codestorm1** [automategreen/dynamoose#58]
I have a table whose schema is shown below.
I need to be able to look up a score item by gameId and userId, to update a user's score.
I also need to be able to look up items by score to fetch items in score order, to show a leaderboard.

I've tried different index/hashKey/rangeKey combinations, but haven't been able to get both queries to work.

Thanks in advance,

Bryan

var schema = new Schema({
  scoreId: {
    type: String,
    required: true,
    hashKey: true
  },
  gameId: {
    type: String,
    required: true,
    rangeKey: true
  },
  score: {
    type: Number,
    required: true,
    index: {
      global: true,
      rangeKey: 'scoreId',
      name: 'ScoreIndex',
      project: true,
      throughput: 5
    }
  },
  userId: {
    type: String,
    required: true,
    index: {
      global: true,
      rangeKey: 'gameId',
      name: 'UserScoreIndex',
      project: true,
      throughput: 5
    }
  },
  createdAt: {
    type: Date
  },
  updatedAt: {
    type: Date
  },
}

**Comment by brandongoode** [comment]
First I would flip the hashKey and rangeKey.  I would also have score be a local index (I'm assuming the top score query would be based on a gameId)

**Disclamer** I have not tested this and there are probably typos

```js
var schema = new Schema({
  gameId: {
    type: String,
    required: true,
    hashKey: true
  },
  scoreId: {
    type: String,
    required: true,
    rangeKey: true
  },
  score: {
    type: Number,
    required: true,
    index: true
  },
  userId: {
    type: String,
    required: true,
    index: {
      global: true,
      rangeKey: 'gameId',
      name: 'UserScoreIndex',
      project: true,
      throughput: 5
    }
  },
  createdAt: {
    type: Date
  },
  updatedAt: {
    type: Date
  }
});


// All scores for a game
Score.query('gameId').eq(gameId) 

// Top 10 scores for a game
Score.query('gameId').eq(gameId).where('score').descending().limit(10)

// All scores for a user
Score.query('userId').eq(userId) 

// All scores for a user for a game
Score.query('userId').eq(userId).where('gameId').eq(gameId)
```

**Comment by codestorm1** [comment]
That did the trick, thanks very much!

**Comment by zuyao1988** [comment]
Hi, for the example above, can I move user to a new schema(table)?


const user = new Schema({
id..
name...
})


and nested/embedded it in the main schema by referring the id?

**Comment by brandongoode** [comment]
@zuyao1988 -- Yes - see the documentation on populate for some examples

https://dynamoosejs.com/api#modelpopulateoptions
