### ISSUE TITLE
Building a query dynamically?

### ISSUE THREAD

**Issue by reselbob** [automategreen/dynamoose#60]
I want to build a search query dynamically using Dynamoose that depends on the parameters sent to me.

for example, if I am passed `startDate` only, I want can do

``` javascript
Model.query('startDate').gt(startDate).exec(function (err, results) {.....};
```

But if by chance I get `status`, of course I can build the query:

``` javascript
Model.query('startDate').eq(startDate)
  .where('status').eq('ACTIVE')
  .exec(function (err, results) {.....};
```

But say I have some conditions where I may or may not be passed a parameter, `scoutMaster`.

Is there a way I can dynamically append the `and` clause condition:

``` javascript
Model.query('startDate').eq(startDate)
  .where('status').eq('ACTIVE')
  .and('scoutMaster').eq(scoutMaster)
  .exec(function (err, results) {.....};
```

Thanks for any help!!!

**Comment by reselbob** [comment]
Might I have to use a conditional expression?

**Comment by reselbob** [comment]
What, I can build the query dynamically this way:
```javascript
Dog.query({breed: {eq: 'Beagle'} }, function (err, dogs) {
  // Look at all the beagles
});
```

by constructing the query object dynamically?

**Comment by reselbob** [comment]
Dynamic query object construction seems to be a viable approach. 
```javascript

function constructQueryObjectForDynamoose(options) {

  let o = {};
  for (let prop in options) {
    if (prop === 'status')o.status = {eq: options[prop]};
    if (prop === 'startDate')o.startDate = {ge: options[prop]};
    if (prop === 'endDate')o.endDate = {le: options[prop]};
  }
  return o;

}
```

However, I am at a loss as to how do date comparisons. Seems the query object attributes for `le`, `ge` and such only support numbers.

**Comment by brandongoode** [comment]
The best way to build a dynamic query (or scan) is to use the query (or scan) object.   In this case you man need to use `.scan`.  Query expect a `.eq` after the range key for the table or index.  

```js
var scan = Model.scan();

for (let prop in options) {
  if (prop === 'status') {
    scan.filter(prop).eq(option[prop]);
  }
  if (prop === 'startDate') {
    scan.filter(prop).ge(options[prop]);
  }
  if (prop === 'endDate') {
    scan.filter(prop).le(options[prop]);
  }
}

scan.exec(function(results) {
  ...
}
```

**Comment by reselbob** [comment]
Thank you!

**Comment by reselbob** [comment]
Also, this is probably tangential, but I still have this problem. When I execute this:
```javascript
    let query = {startDate:{ge:new Date("July 21, 1983")}};
    Challenge.query(query, function (err, challenges)
``` 
I get this error:

_**A value provided cannot be converted into a number**_

Seems that the `ge` operator does not like dates. If I am correct, is there a work around?

If am in error, what do I need to differently?

Thanks in advance.

**Comment by brandongoode** [comment]
The error is not correct.  This issue is related to the fact that a query requires an `eq` for the hash key. 

This needs to be corrected as several other have had the same issue. #59
