### ISSUE TITLE
Integrate with Joi? 

### ISSUE THREAD

**Issue by zkhalapyan** [automategreen/dynamoose#62]
Implementing custom validation functions is tedious — having integration with [Joi](https://github.com/hapijs/joi) would let us delegate some of the heavy validation logic to another module.

You can see example setup in Vogels: https://github.com/ryanfitz/vogels#define-a-model

Is this something people would be interested in?

**Comment by brandongoode** [comment]
Sounds like a great idea.  We may be able quickly make it work with the current `validate` options. 

Something like (untested):

```js
new Schema({
  email: {
    type: String,
    validate: function(v) {
      var result = Joi.validate(v, Joi.string().email());
      return !result.error;
    }
  }
  ...
});
```

**Comment by vinyoliver** [comment]
Any news on this? Couldn't find anything related

**Comment by dolsem** [comment]
@vinyoliver Dynamoose schema fields support `validate` prop. You can set it to `validate` method of your Joi schema, for example.
