### ISSUE TITLE
Deploying new and modified indexes without having to delete and restore tables?

### ISSUE THREAD

**Issue by reselbob** [automategreen/dynamoose#66]
Hi:

It seems that whenever I add a new index to a model, or modify an index, I get errors in the console that say, to paraphrase, "Index not in table".

Thus, I nuke the table from AWS and start over.

This is OK for DEV and TEST, but won't do in PRODUCTION. 

Tell me please what is the best practice for adding/modifying indexes in Dynamoose models that allow for deployment on existing tables in AWS?

Thanks in advance.

Bob

**Comment by brandongoode** [comment]
Originally DynamoDB didn't let you add indexes, but the ability to add indexes has existed for 18 months now.  I really need to go back and add the logic (just short on time).  I have an open issues to add this: #11. 

For now, you can go into the DynamoDB console and add the index manually.

**Comment by reselbob** [comment]
Thank you!
