### ISSUE TITLE
Validation on query/get?

### ISSUE THREAD

**Issue by James-Firth** [automategreen/dynamoose#68]
I'm using the `.get` and `.query` functions to find data in my db.

If I pass a value that fails the validation for that Model/Schema the `get` throws an error (uncaught by the `catch` in the Promise) and crashes my server.

Why is it that the error is thrown in such a way the Promise doesn't catch it? Or is there a better way for me to be handling this?

My current solution is to wrap those lookup functions in try/catch blocks but that's ugly and seems to go against the idea of Promises.

Thanks for any help

**Comment by brandongoode** [comment]
Sounds like a bug, I'll try to duplicate it.  Can you provide the code that causes the crash and the attribute schema validation?

**Comment by brandongoode** [comment]
I'm pretty sure I know where the issue is.  I'll try to get a fix in this week.

**Comment by James-Firth** [comment]
Sure here's a summary of the spots in my code that seem to be causing issues and awesome! Glad you have an idea of where to look.

I've got a user schema that contains a v4 UUID that uses a regex to validate it's a proper UUID
```
    id: {
      type: String,
      hashKey: true,
      required: true,
      trim: true,
      default: uuid.v4,
      validate: /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
     }
```
I set the model named `User` and whenever I did `User.get({ id: userID });` where `userID` is *not* a v4 UUID it would throw an error so I had to put it in a try/catch block.

**Comment by James-Firth** [comment]
Hey @brandongoode just wondering if you'd had a chance to work on this at all?

**Comment by brandongoode** [comment]
Thanks for the reminder -- I'll work on the fix now.

**Comment by James-Firth** [comment]
Awesome thanks! Glad it was a quick fix :)
