### ISSUE TITLE
[Question] How do I get latest element by createdDate field?

### ISSUE THREAD

**Issue by Shalimov** [automategreen/dynamoose#69]
Is there an optimal way how to get latest element by date?
Cuz get all records from table seems not really good.

**Comment by brandongoode** [comment]
My approaches is to use the date as a range key then use `queryOne()` with `descending()` to get the latest.  Here's and example from my code:

```js
var latestStatus = yield Status.queryOne('deviceId')
  .eq(deviceId)
  .where('date')
  .descending()
  .exec();
```

**Comment by Shalimov** [comment]
Thanks for your prompt reply) It is really helpful!)

**Comment by Shalimov** [comment]
One more question to clarify:
How to set rangeKey for timestamp createAt or updateAt, cuz in schema config I use timestamp option

**Comment by brandongoode** [comment]
Good point -- I don't think you can using the timestamp option.

You'll have to manually define the two attributes. 

```js
var schema = new Schema({
  ...
  createAt: {
    type: Date,
    default: Date.now,
    index: true
  },
  updateAt: {
    type: Date,
    set: Date.now,
    index: true
  },
  ...
});

**Comment by Shalimov** [comment]
Thx again, it is good. What do you think about the following: So right now I have records in table without indexes on (createAt, updateAt), are the some issues after I change the scheme to provide indexes? Does dynamodb apply indexes automatically for existed records?

**Comment by brandongoode** [comment]
That's a limitation of the local indexes. Per Amazon "Local secondary indexes are created at the same time that you create a table. You cannot add a local secondary index to an existing table, nor can you delete any local secondary indexes that currently exist."


You can create a global index manually (i.e. dynamoose can't create it after the table is created) and have the createAt field be the range key for that global index, but other than that you'll have do create a new table and migrate the data.

**Comment by Shalimov** [comment]
Do I need to use ```.and``` when use several conditions in filter,
and what type of data should I use in filter for timestamps (Date or  simple Timestamp(Number)) 

```javascript
self.Entity.scan({
            ownerId: {
                eq: req.queryString.userId
            },
            createdAt: {
                ge: moment().subtract(10, 'days')
            }
        }).and().exec()
```
