### ISSUE TITLE
how to create password?

### ISSUE THREAD

**Issue by arulsiva** [automategreen/dynamoose#71]
var Schema = dynamoose.Schema; 
const authTypes = ['facebook', 'google'];
var UserSchema = new Schema({
  _id: String,
  email: {
    type: String,
    hashKey: true
  },
  name:String,
  hashedPassword: String,
  provider: String,
  role: String,
  salt: String
});

UserSchema
   .path('hashedPassword')
.validate(function(hashedPassword) {
 if(authTypes.indexOf(this.provider) !== -1) {
  return respond(true);
   }
  return hashedPassword.length;
 }, 'Password cannot be blank');

this is mongoos setup 
how can implement using dynamoose ?

**Comment by brandongoode** [comment]
Sorry for the slow response.

Are you looking to just validate the password or generate one?


To validate it you would add a validate function to the `hashedPassword` attribute:

```js
var Schema = dynamoose.Schema; 
const authTypes = ['facebook', 'google'];
var UserSchema = new Schema({
  _id: String,
  email: {
    type: String,
    hashKey: true
  },
  name:String,
  hashedPassword: {
    type: String,
    validate: function (hashedPassword) { hashedPassword.length > 0 }
  },
  provider: {
    type: String,
    validate: function (provider) { authTypes.indexOf(provider) !== -1 }
  },
  role: String,
  salt: String
});
```

If you want to generate a the hash from a password, you could use a virtual attribute:

```js
schema.virtual('password').set(function(password){
  this.hashedPassword = hashPassword(password);
});

```

**Comment by josiekre** [comment]
I'm trying to follow this example, but am getting an error: "Required value missing: hashedPassword"

    UserSchema.virtual('password').set(function(password) {
      var user = this;
      bcrypt.hash(password, 10, function(err, hash) {
        if (err) {
          return callback(err);
        }
        user.hashedPassword = hash;
      });
    });

Any idea why?

**Comment by brandongoode** [comment]
I think it is the fact the set function doesn't wait for the `bcrypt.hash` to return.  It expects the set function to be synchronous.

Instead of a virtual you may want to use a static. 

Here is more or less  what I do for my user model:

```js

User.resetPassword = function *(u) {
  var user = yield User.queryOne('email').eq(u.email).exec();
  user.password = yield hash(u.password, 10);
  yield user.save();
  return user;
}

**Comment by josiekre** [comment]
That's a good thought. I tried a version of your method to no avail. I went back to the original, and found a sync version:

    UserSchema.virtual('password').set(function(password) {
      this.hashedPassword = bcrypt.hashSync(password, 10);
    });

Still doesn't work. "Required value missing: hashedPassword" I'll keep hacking away. Let me know if you have any more thoughts.

**Comment by brandongoode** [comment]
There may be an issue with the order virtuals setter are applied.  Still looking into that.  

I know my method will work if you want to give that a try in the meantime.

**Comment by josiekre** [comment]
Thanks. I've got it working with a simple static method.

    // Hash password
    User.hash = function(password) {
      return bcrypt.hashSync(password, 10);
    };

    // To create a user:
    var userData = {
      email: req.body.registerEmail.toLowerCase(),
      password: User.hash(req.body.registerPassword)
    };

    // Use schema's `create` method to insert document into database
    User.create(userData, ... });
