### ISSUE TITLE
dynamoose.local() does not work

### ISSUE THREAD

**Issue by frankbolviken** [automategreen/dynamoose#72]
Hi,

When adding the dynamoose.local() config, it still connects to AWS dynamodb instance.

What am I missing?

F

**Comment by frankbolviken** [comment]
Silly me was not issuing dynamoose.local() in the correct place.

**Comment by dpkshrma** [comment]
@frankbolviken I am facing the same issue, where did you specify `dynamoose.local()`? I tried putting it in the server script and models, neither worked. And, it's not showing any errors either.

**Comment by miguelduarte42** [comment]
I had the same issue. The solution is to run dynamoose.local() before running dynamoose.model(). As it seems, the models keep a copy of the endpoint that was defined at modeling time, which means that running dynamoose.local() afterwards will have no effect

Run your app with DEBUG=dynamoose to see the order in which they run.
