### ISSUE TITLE
[Question] Typescript Support

### ISSUE THREAD

**Issue by jpinkster** [automategreen/dynamoose#77]
Has anyone created a typings file for this project yet? I thought I saw one but cannot find it.

**Comment by brandongoode** [comment]
I do not know of one.  If you find (or create one) I would be glad to link to it.

**Comment by rvaidya** [comment]
@jpinkster Did you ever find those definitions?  Since dynamoose uses plain javascript objects for save and get, it seems like it's the best mapper out there to use with Typescript for strongly typed models.

**Comment by rvaidya** [comment]
@brandongoode I've been working on my own version of typings, would you want to incorporate them into the repo or would you prefer them to be in DefinitelyTyped?

I don't think they're correct yet so I'd be reluctant to publish them to DefinitelyTyped.

**Comment by brandongoode** [comment]
@rvaidya & @jpinkster 

I'm not overly familiar with Typescript (understand the basics, but I've never used it).  So I'm not sure I know where the best place to have the typings.  I don't mind them being within this repo or linking to an external repo.  My concern about them being within dynamoose is the ongoing support.   

What are your thoughts?

**Comment by jpinkster** [comment]
Well you have 2 options:

1. Create a repo under your account and then register them with typings (https://github.com/typings/registry: follow readme)

2. Fork https://github.com/DefinitelyTyped/DefinitelyTyped and create a PR to push them into here

I would do option 1 because then you get the credit and have full control

**Comment by rvaidya** [comment]
Putting it up on DefinitelyTyped would require some cleanup and testing since they've got quality control for submissions, but that's probably the best way since others can contribute to it independently of the package itself.

I've created a Gist with the definition here, it's still missing stuff and I haven't been able to test Query/Scan yet.

https://gist.github.com/rvaidya/27017a6495fedc27282e7df9e7727529

**Comment by breath103** [comment]
is there anyone working on this? i'm building this now so it would be great if there anyone i can work with!

**Comment by breath103** [comment]
which is i ended up making it hahha https://gist.github.com/breath103/24d19be98724bf3c88a5907f4d65dca6
i'm not gonna do further work now, but for anyone who need this here it is

**Comment by strygin** [comment]
Cool, thanks! I need this. Can it be added to repo? We can't keep on Gist :)

**Comment by breath103** [comment]
honestly best would be just re-write dynamoose in typescript (which i think really good idea) @strygin how do you feel like about that?

**Comment by strygin** [comment]
I wouldn't do that, too much low-level code in dynamoose, it's practically a driver. I'd prefer native ES6-sugaring, getting rid of outdated stuff like `util.inherits()`...
Probably `d.ts` for IDE convenience is enough.

**Comment by breath103** [comment]
hm.. that make sense, but also if you consider all the things we could do with typescript template class i feel like it's still considerable.
but anyway that's a HUGE work haha. i'm using dynamoose + typescript on production already, so i'll let you know after submitting that to @types.

**Comment by mizchi** [comment]
FYI, I wrote flowtype definition file for myself (only for promise API). https://gist.github.com/mizchi/bc865dc0e68af33a96810116e1d529b1
