### ISSUE TITLE
I would like to query passing an object in this way, like mongoose.

### ISSUE THREAD

**Issue by levarne** [automategreen/dynamoose#80]
**I currently have this:**
`dynamoose.query('accountId').eq('123456789890').where('created').between('2016-12-24',` `'2016-12-24').exec()`

**I want to do this:**
 `query = {`
            `'accountId': {`
                    `'eq': query['id']`
          `  },`
           ` 'created': {`
                    `'between': [query['startDate'], query['endDate']]`
        `    }`
        `}`
 `dynamoose.query(query)`

**Comment by brandongoode** [comment]
@levarne - You can use an object, but it's not well documented. You have to define what the hash and range keys are in the object. 

It would look something like this:

```js
dynamoose.query({
  hash: { accountId: {eq: id },
  range: { created: { between: [startDate,  endDate] }
});
```

Sorry for the slow response.

**Comment by levarne** [comment]
wow thanks alot.
