### ISSUE TITLE
Support for Promises for functions with callbacks

### ISSUE THREAD

**Issue by rvaidya** [automategreen/dynamoose#82]
It would be useful to add support for Promises for the functions with callbacks (ie. query.exec, scan.exec, etc)

**Comment by brandongoode** [comment]
It does.  

Here's an example:

```
var query = Something.query('id').eq('abc123');
query.exec()
.then(function (things) {
  ...
})
.catch(function (err) {
 ...
});

**Comment by rvaidya** [comment]
Oh cool, I'll need to reflect that in the typescript definition
