### ISSUE TITLE
Boolean field default value

### ISSUE THREAD

**Issue by JohanWillfred** [automategreen/dynamoose#83]
I have a schema like this 
`new Schema({
        id: {
            type: String,
            hashKey: true
        },
        code: {
            type: String,
            trim: true,
            required: true
        },
        currency: {
            type: String,
            trim: true
        },
        deleted: {
            type: Boolean,
            default: false
        }
    },
    {
        throughput: {read: 5, write: 5}
    })`

Inserted objects will have string type for field "deleted" (not boolean) is it correct schema behavior ?
`{
  "code": "QWERTY_1",
  "currency": "USD",
  "deleted": "false",
  "id": "89e0c249dec26924386d19f0188fb25f87e4b0eb"
}`

**Comment by brandongoode** [comment]
You are correct.  It will be stored in DynamoDB as a string.  Dynamoose will convert it back to a boolean when it loads the value.  

Dynmoose predates DynamoDB's support for booleans.  I've been meeting to add a flag that would allow you to configure if the attribute used a native Boolean or was converted to a String.

**Comment by JohanWillfred** [comment]
@brandongoode Thanks for your response)

**Comment by brandongoode** [comment]
Closing will track under #55
