### ISSUE TITLE
Use the same hash key on table in GSI

### ISSUE THREAD

**Issue by shineli1984** [automategreen/dynamoose#86]
https://github.com/automategreen/dynamoose/blob/master/lib/Query.js#L80 
prevents from using the same hash key on table in a GSI.

Is there any work around for this?

**Comment by brandongoode** [comment]
Not today (PR welcome) -- Sorry for the slow response.

**Comment by aloof-ruf** [comment]
I have a suggestion for this issue. What if `index` accepted both an object defining the GSI/LSI or an array specifying multiple GSIs/LSIs on that particular attribute?

It could look something like this:

```js
var newSchema = new dynamoose.Schema({
  id: Number,
  thing: {
    type: String
    index: [
    {
      global: true
      projection: ['a1', 'a2', ...],
    },
    {
      global: true
      projection: ['a5', 'a7', ...],
    }
    ]
  }
...
})
```

Default names could be appended with their position in the array, resulting in names like `attrNameGlobalIndex0`.

@shineli1984 @brandongoode what do you two think about this solution. I don't mind making a PR for it

**Comment by brandongoode** [comment]
I like it.

We would also need a way to identify the index to use for a query.   What about `query.using(indexName)`?  The default would be the first index or the main table if the attribute is the table key.

**Comment by aloof-ruf** [comment]
Alright, I'm moving on that PR right now. I'll use your `query.using(indexName)` idea as well.

**Comment by cbarrese** [comment]
@aloof-ruf have you done any work on this?  We are looking for the same functionality, and we can  help contribute if you have already made some progress but don't have the time to finish it.
