### ISSUE TITLE
Help Needed - Collaborator

### ISSUE THREAD

**Issue by brandongoode** [automategreen/dynamoose#87]
If anyone is interested in helping support this repo, please let me know.  I need help answering questions, fixing issues and improving the documentation.

**Comment by treyhuffine** [comment]
I'm transitioning from other databases to DynamoDB / dynamoose. I'm not sure if I'm invested enough or experienced enough with the technology yet to become a collaborator, but I would be happy to submit PR's as much as I can until that point. I'm a huge fan of the package.

**Comment by brandongoode** [comment]
@treyhuffine - That would be awesome!

**Comment by troyswanson** [comment]
I'm interested in helping but I'm still pretty new to DynamoDB in general.

Added myself as a Watcher so that I can get insight into everything that's going on.

**Comment by brandongoode** [comment]
@troyswanson -- That's great.  Thanks for the support.
