### ISSUE TITLE
Parallel Scan?

### ISSUE THREAD

**Issue by jongnam** [automategreen/dynamoose#90]
my DynamoDB table has 10k+ items, and the scan() takes time. Meanwhile, DynamoDB supports parallel scan. 

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#QueryAndScanParallelScan
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html

Does Dynamoose have plan to support it?

**Comment by brandongoode** [comment]
I didn't have plans to add it, but now I do. No time comment yet. 

I'm thinking something like `scan.pareallel(numOfSegments)`  and the results would be merged back into a single array and the `lastKey` would be an array that could be passed to `scan.startAt(lastKey)`.

What are your thoughts on how it should work?

**Comment by jongnam** [comment]
Thank you Brandon.

Yes I am with your idea, and let me give few thoughts. I imagine a new method such as `parallelScan(numOfSegments)`. And under the hood, it executes `scan()` with additional parameters `segmentIndex`, and `numOfSegments`. The individual scan operation would behave the same as existing scan, including the `lastKey` behavior.  In the end, the `parallelScan()` would return the single array of result along with a list of `lastKey`s.
  
In addition, from my own case, I just want to pull every data without handling `lastKey` from my code. In other words, if dynamoose has an option to automatically call series of `scan()` with subsequent lastKey's, then I can simply rely on `scan()` to pull entire data from DynamoDB table.

Same wish applies to `parallelScan()` too. I wish `parallelScan() `automatically execute `scan()` in parallel, and the each `scan()` pulls subsequent data using series of `scans()`. For instance, when I call `parallelScan(8)`, there would be 8 `scan() `tasks run in parallel. And the individual `scan()` would keep calling `scan()` until its prior `scan()` does not return `lastKey` value.

**Comment by brandongoode** [comment]
Sounds good.  I've opened a second issue, #93, to track scanning all items.

**Comment by strygin** [comment]
I will implement this. Probably this week.

**Comment by brandongoode** [comment]
Cool thanks
