### ISSUE TITLE
New feature: scan.all()

### ISSUE THREAD

**Issue by brandongoode** [automategreen/dynamoose#93]
Add support for scan to recusivly scan while `lastKey` exists.

```js
scan.all([delay[, max]])
```

`delay` is the time between recursive scans.  Default: 1sec

`max` is the maximum number of recursive scans. Default: 0 - unlimited

**Comment by strygin** [comment]
Why do we need delay? ;-\

**Comment by brandongoode** [comment]
The thought behind the delay is to allow the request to be throttled.

**Comment by fishcharlie** [comment]
@brandongoode Close this issue? 😃 👍
